// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.2
// source: cart.proto

package Protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCartSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCountry   string                 `protobuf:"bytes,1,opt,name=user_country,json=userCountry,proto3" json:"user_country,omitempty"` //国家地区
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Navdata       *Navdata               `protobuf:"bytes,3,opt,name=navdata,proto3" json:"navdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartSend) Reset() {
	*x = AddCartSend{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartSend) ProtoMessage() {}

func (x *AddCartSend) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartSend.ProtoReflect.Descriptor instead.
func (*AddCartSend) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *AddCartSend) GetUserCountry() string {
	if x != nil {
		return x.UserCountry
	}
	return ""
}

func (x *AddCartSend) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AddCartSend) GetNavdata() *Navdata {
	if x != nil {
		return x.Navdata
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packageid     uint32                 `protobuf:"varint,1,opt,name=packageid,proto3" json:"packageid,omitempty"`               //捆绑包
	Bundleid      uint32                 `protobuf:"varint,2,opt,name=bundleid,proto3" json:"bundleid,omitempty"`                 //购物车ID
	GiftInfo      *GiftInfo              `protobuf:"bytes,10,opt,name=gift_info,json=giftInfo,proto3" json:"gift_info,omitempty"` //礼物信息
	Flag          *Flag                  `protobuf:"bytes,11,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetPackageid() uint32 {
	if x != nil {
		return x.Packageid
	}
	return 0
}

func (x *Item) GetBundleid() uint32 {
	if x != nil {
		return x.Bundleid
	}
	return 0
}

func (x *Item) GetGiftInfo() *GiftInfo {
	if x != nil {
		return x.GiftInfo
	}
	return nil
}

func (x *Item) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

type CuratorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clanid        uint32                 `protobuf:"varint,1,opt,name=clanid,proto3" json:"clanid,omitempty"`
	Listid        uint64                 `protobuf:"varint,2,opt,name=listid,proto3" json:"listid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CuratorData) Reset() {
	*x = CuratorData{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CuratorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CuratorData) ProtoMessage() {}

func (x *CuratorData) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CuratorData.ProtoReflect.Descriptor instead.
func (*CuratorData) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CuratorData) GetClanid() uint32 {
	if x != nil {
		return x.Clanid
	}
	return 0
}

func (x *CuratorData) GetListid() uint64 {
	if x != nil {
		return x.Listid
	}
	return 0
}

type Navdata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Controller    string                 `protobuf:"bytes,2,opt,name=controller,proto3" json:"controller,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Submethod     string                 `protobuf:"bytes,4,opt,name=submethod,proto3" json:"submethod,omitempty"`
	Feature       string                 `protobuf:"bytes,5,opt,name=feature,proto3" json:"feature,omitempty"`
	Depth         uint32                 `protobuf:"varint,6,opt,name=depth,proto3" json:"depth,omitempty"`
	Countrycode   string                 `protobuf:"bytes,7,opt,name=countrycode,proto3" json:"countrycode,omitempty"`
	Webkey        string                 `protobuf:"bytes,8,opt,name=webkey,proto3" json:"webkey,omitempty"`
	IsClient      bool                   `protobuf:"varint,9,opt,name=is_client,json=isClient,proto3" json:"is_client,omitempty"`
	CuratorData   *CuratorData           `protobuf:"bytes,10,opt,name=curator_data,json=curatorData,proto3" json:"curator_data,omitempty"`
	IsLikelyBot   bool                   `protobuf:"varint,11,opt,name=is_likely_bot,json=isLikelyBot,proto3" json:"is_likely_bot,omitempty"`
	IsUtm         bool                   `protobuf:"varint,12,opt,name=is_utm,json=isUtm,proto3" json:"is_utm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Navdata) Reset() {
	*x = Navdata{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Navdata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navdata) ProtoMessage() {}

func (x *Navdata) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navdata.ProtoReflect.Descriptor instead.
func (*Navdata) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *Navdata) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Navdata) GetController() string {
	if x != nil {
		return x.Controller
	}
	return ""
}

func (x *Navdata) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Navdata) GetSubmethod() string {
	if x != nil {
		return x.Submethod
	}
	return ""
}

func (x *Navdata) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *Navdata) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Navdata) GetCountrycode() string {
	if x != nil {
		return x.Countrycode
	}
	return ""
}

func (x *Navdata) GetWebkey() string {
	if x != nil {
		return x.Webkey
	}
	return ""
}

func (x *Navdata) GetIsClient() bool {
	if x != nil {
		return x.IsClient
	}
	return false
}

func (x *Navdata) GetCuratorData() *CuratorData {
	if x != nil {
		return x.CuratorData
	}
	return nil
}

func (x *Navdata) GetIsLikelyBot() bool {
	if x != nil {
		return x.IsLikelyBot
	}
	return false
}

func (x *Navdata) GetIsUtm() bool {
	if x != nil {
		return x.IsUtm
	}
	return false
}

type GiftInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountidGiftee   int32                  `protobuf:"varint,1,opt,name=accountid_giftee,json=accountidGiftee,proto3" json:"accountid_giftee,omitempty"`
	GiftMessage       *GiftMessage           `protobuf:"bytes,2,opt,name=gift_message,json=giftMessage,proto3" json:"gift_message,omitempty"`
	TimeScheduledSend int32                  `protobuf:"varint,3,opt,name=time_scheduled_send,json=timeScheduledSend,proto3" json:"time_scheduled_send,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GiftInfo) Reset() {
	*x = GiftInfo{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftInfo) ProtoMessage() {}

func (x *GiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftInfo.ProtoReflect.Descriptor instead.
func (*GiftInfo) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *GiftInfo) GetAccountidGiftee() int32 {
	if x != nil {
		return x.AccountidGiftee
	}
	return 0
}

func (x *GiftInfo) GetGiftMessage() *GiftMessage {
	if x != nil {
		return x.GiftMessage
	}
	return nil
}

func (x *GiftInfo) GetTimeScheduledSend() int32 {
	if x != nil {
		return x.TimeScheduledSend
	}
	return 0
}

type GiftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gifteename    string                 `protobuf:"bytes,1,opt,name=gifteename,proto3" json:"gifteename,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sentiment     string                 `protobuf:"bytes,3,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiftMessage) Reset() {
	*x = GiftMessage{}
	mi := &file_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftMessage) ProtoMessage() {}

func (x *GiftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftMessage.ProtoReflect.Descriptor instead.
func (*GiftMessage) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{5}
}

func (x *GiftMessage) GetGifteename() string {
	if x != nil {
		return x.Gifteename
	}
	return ""
}

func (x *GiftMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GiftMessage) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *GiftMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type Flag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsGift        bool                   `protobuf:"varint,1,opt,name=is_gift,json=isGift,proto3" json:"is_gift,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,2,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{6}
}

func (x *Flag) GetIsGift() bool {
	if x != nil {
		return x.IsGift
	}
	return false
}

func (x *Flag) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type AddCartReceive struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	LineItemIds                           []uint64               `protobuf:"varint,1,rep,packed,name=line_item_ids,json=lineItemIds,proto3" json:"line_item_ids,omitempty"`
	Cart                                  *Cart                  `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	ReplacedPackages                      []uint32               `protobuf:"varint,3,rep,packed,name=replaced_packages,json=replacedPackages,proto3" json:"replaced_packages,omitempty"`
	ExistingBillingAgreementid            uint64                 `protobuf:"varint,4,opt,name=existing_billing_agreementid,json=existingBillingAgreementid,proto3" json:"existing_billing_agreementid,omitempty"`
	NewBillingAgreementRecurringPackageid uint32                 `protobuf:"varint,5,opt,name=new_billing_agreement_recurring_packageid,json=newBillingAgreementRecurringPackageid,proto3" json:"new_billing_agreement_recurring_packageid,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *AddCartReceive) Reset() {
	*x = AddCartReceive{}
	mi := &file_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartReceive) ProtoMessage() {}

func (x *AddCartReceive) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartReceive.ProtoReflect.Descriptor instead.
func (*AddCartReceive) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{7}
}

func (x *AddCartReceive) GetLineItemIds() []uint64 {
	if x != nil {
		return x.LineItemIds
	}
	return nil
}

func (x *AddCartReceive) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *AddCartReceive) GetReplacedPackages() []uint32 {
	if x != nil {
		return x.ReplacedPackages
	}
	return nil
}

func (x *AddCartReceive) GetExistingBillingAgreementid() uint64 {
	if x != nil {
		return x.ExistingBillingAgreementid
	}
	return 0
}

func (x *AddCartReceive) GetNewBillingAgreementRecurringPackageid() uint32 {
	if x != nil {
		return x.NewBillingAgreementRecurringPackageid
	}
	return 0
}

// 修改
type ModifyCartSend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LineItemId     uint64                 `protobuf:"varint,1,opt,name=line_item_id,json=lineItemId,proto3" json:"line_item_id,omitempty"`
	UserCountry    string                 `protobuf:"bytes,2,opt,name=user_country,json=userCountry,proto3" json:"user_country,omitempty"`
	GiftInfo       *GiftInfo              `protobuf:"bytes,10,opt,name=gift_info,json=giftInfo,proto3" json:"gift_info,omitempty"`
	Flag           *Flag                  `protobuf:"bytes,11,opt,name=flag,proto3" json:"flag,omitempty"`
	ApplyGidcoupon uint64                 `protobuf:"varint,12,opt,name=apply_gidcoupon,json=applyGidcoupon,proto3" json:"apply_gidcoupon,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModifyCartSend) Reset() {
	*x = ModifyCartSend{}
	mi := &file_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyCartSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyCartSend) ProtoMessage() {}

func (x *ModifyCartSend) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyCartSend.ProtoReflect.Descriptor instead.
func (*ModifyCartSend) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyCartSend) GetLineItemId() uint64 {
	if x != nil {
		return x.LineItemId
	}
	return 0
}

func (x *ModifyCartSend) GetUserCountry() string {
	if x != nil {
		return x.UserCountry
	}
	return ""
}

func (x *ModifyCartSend) GetGiftInfo() *GiftInfo {
	if x != nil {
		return x.GiftInfo
	}
	return nil
}

func (x *ModifyCartSend) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *ModifyCartSend) GetApplyGidcoupon() uint64 {
	if x != nil {
		return x.ApplyGidcoupon
	}
	return 0
}

// 修改返回值
type ModifyCartReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyCartReceive) Reset() {
	*x = ModifyCartReceive{}
	mi := &file_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyCartReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyCartReceive) ProtoMessage() {}

func (x *ModifyCartReceive) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyCartReceive.ProtoReflect.Descriptor instead.
func (*ModifyCartReceive) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyCartReceive) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type Cart struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LineItems         []*LineItem            `protobuf:"bytes,1,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	Subtotal          []*Price               `protobuf:"bytes,2,rep,name=subtotal,proto3" json:"subtotal,omitempty"`
	IsValid           bool                   `protobuf:"varint,3,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ValidationDetails []*ValidationFailure   `protobuf:"bytes,4,rep,name=validation_details,json=validationDetails,proto3" json:"validation_details,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{10}
}

func (x *Cart) GetLineItems() []*LineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *Cart) GetSubtotal() []*Price {
	if x != nil {
		return x.Subtotal
	}
	return nil
}

func (x *Cart) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *Cart) GetValidationDetails() []*ValidationFailure {
	if x != nil {
		return x.ValidationDetails
	}
	return nil
}

type LineItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LineItemId        uint64                 `protobuf:"varint,1,opt,name=line_item_id,json=lineItemId,proto3" json:"line_item_id,omitempty"`
	Type              uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Packageid         uint32                 `protobuf:"varint,3,opt,name=packageid,proto3" json:"packageid,omitempty"`
	Bundleid          uint32                 `protobuf:"varint,4,opt,name=bundleid,proto3" json:"bundleid,omitempty"`
	IsValid           bool                   `protobuf:"varint,8,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ValidationDetails *ValidationFailure     `protobuf:"bytes,9,opt,name=validation_details,json=validationDetails,proto3" json:"validation_details,omitempty"`
	TimeAdded         uint32                 `protobuf:"varint,10,opt,name=time_added,json=timeAdded,proto3" json:"time_added,omitempty"`
	PriceWhenAdded    *Price                 `protobuf:"bytes,11,opt,name=price_when_added,json=priceWhenAdded,proto3" json:"price_when_added,omitempty"`
	GiftInfo          *GiftInfo              `protobuf:"bytes,12,opt,name=gift_info,json=giftInfo,proto3" json:"gift_info,omitempty"`
	Flag              *Flag                  `protobuf:"bytes,13,opt,name=flag,proto3" json:"flag,omitempty"`
	GidcouponApplied  uint64                 `protobuf:"varint,14,opt,name=gidcoupon_applied,json=gidcouponApplied,proto3" json:"gidcoupon_applied,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{11}
}

func (x *LineItem) GetLineItemId() uint64 {
	if x != nil {
		return x.LineItemId
	}
	return 0
}

func (x *LineItem) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LineItem) GetPackageid() uint32 {
	if x != nil {
		return x.Packageid
	}
	return 0
}

func (x *LineItem) GetBundleid() uint32 {
	if x != nil {
		return x.Bundleid
	}
	return 0
}

func (x *LineItem) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *LineItem) GetValidationDetails() *ValidationFailure {
	if x != nil {
		return x.ValidationDetails
	}
	return nil
}

func (x *LineItem) GetTimeAdded() uint32 {
	if x != nil {
		return x.TimeAdded
	}
	return 0
}

func (x *LineItem) GetPriceWhenAdded() *Price {
	if x != nil {
		return x.PriceWhenAdded
	}
	return nil
}

func (x *LineItem) GetGiftInfo() *GiftInfo {
	if x != nil {
		return x.GiftInfo
	}
	return nil
}

func (x *LineItem) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *LineItem) GetGidcouponApplied() uint64 {
	if x != nil {
		return x.GidcouponApplied
	}
	return 0
}

type ValidationFailure struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ValidationFailure uint32                 `protobuf:"varint,1,opt,name=validation_failure,json=validationFailure,proto3" json:"validation_failure,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidationFailure) Reset() {
	*x = ValidationFailure{}
	mi := &file_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationFailure) ProtoMessage() {}

func (x *ValidationFailure) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationFailure.ProtoReflect.Descriptor instead.
func (*ValidationFailure) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{12}
}

func (x *ValidationFailure) GetValidationFailure() uint32 {
	if x != nil {
		return x.ValidationFailure
	}
	return 0
}

type Price struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AmountInCents   int64                  `protobuf:"varint,1,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	CurrencyCode    int32                  `protobuf:"varint,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	FormattedAmount string                 `protobuf:"bytes,3,opt,name=formatted_amount,json=formattedAmount,proto3" json:"formatted_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_cart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{13}
}

func (x *Price) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *Price) GetCurrencyCode() int32 {
	if x != nil {
		return x.CurrencyCode
	}
	return 0
}

func (x *Price) GetFormattedAmount() string {
	if x != nil {
		return x.FormattedAmount
	}
	return ""
}

// 信息显示
type CartInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CartItems       []*CartItem            `protobuf:"bytes,1,rep,name=cart_items,json=cartItems,proto3" json:"cart_items,omitempty"`
	EstimatedTotals []*Estimate            `protobuf:"bytes,5,rep,name=estimated_totals,json=estimatedTotals,proto3" json:"estimated_totals,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CartInfo) Reset() {
	*x = CartInfo{}
	mi := &file_cart_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfo) ProtoMessage() {}

func (x *CartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfo.ProtoReflect.Descriptor instead.
func (*CartInfo) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{14}
}

func (x *CartInfo) GetCartItems() []*CartItem {
	if x != nil {
		return x.CartItems
	}
	return nil
}

func (x *CartInfo) GetEstimatedTotals() []*Estimate {
	if x != nil {
		return x.EstimatedTotals
	}
	return nil
}

type CartItem struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	LineItemId                  uint64                 `protobuf:"varint,1,opt,name=line_item_id,json=lineItemId,proto3" json:"line_item_id,omitempty"`
	ItemId                      *ItemID                `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	StoreItem                   *StoreItem             `protobuf:"bytes,3,opt,name=store_item,json=storeItem,proto3" json:"store_item,omitempty"`
	GiftInfo                    *GiftInfo              `protobuf:"bytes,4,opt,name=gift_info,json=giftInfo,proto3" json:"gift_info,omitempty"`
	Errors                      uint32                 `protobuf:"varint,5,opt,name=errors,proto3" json:"errors,omitempty"`     // ?
	Warnings                    uint32                 `protobuf:"varint,6,opt,name=warnings,proto3" json:"warnings,omitempty"` // ?
	Subtotal                    *Price                 `protobuf:"bytes,7,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	PriceWhenAdded              *Price                 `protobuf:"bytes,8,opt,name=price_when_added,json=priceWhenAdded,proto3" json:"price_when_added,omitempty"`
	OriginalPrice               *Price                 `protobuf:"bytes,9,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	CouponApplied               uint32                 `protobuf:"varint,10,opt,name=coupon_applied,json=couponApplied,proto3" json:"coupon_applied,omitempty"` // ?
	CouponDiscount              *Price                 `protobuf:"bytes,11,opt,name=coupon_discount,json=couponDiscount,proto3" json:"coupon_discount,omitempty"`
	CanPurchaseAsGift           bool                   `protobuf:"varint,12,opt,name=can_purchase_as_gift,json=canPurchaseAsGift,proto3" json:"can_purchase_as_gift,omitempty"`
	RestrictAddAdditionalToCart bool                   `protobuf:"varint,13,opt,name=restrict_add_additional_to_cart,json=restrictAddAdditionalToCart,proto3" json:"restrict_add_additional_to_cart,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cart_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{15}
}

func (x *CartItem) GetLineItemId() uint64 {
	if x != nil {
		return x.LineItemId
	}
	return 0
}

func (x *CartItem) GetItemId() *ItemID {
	if x != nil {
		return x.ItemId
	}
	return nil
}

func (x *CartItem) GetStoreItem() *StoreItem {
	if x != nil {
		return x.StoreItem
	}
	return nil
}

func (x *CartItem) GetGiftInfo() *GiftInfo {
	if x != nil {
		return x.GiftInfo
	}
	return nil
}

func (x *CartItem) GetErrors() uint32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *CartItem) GetWarnings() uint32 {
	if x != nil {
		return x.Warnings
	}
	return 0
}

func (x *CartItem) GetSubtotal() *Price {
	if x != nil {
		return x.Subtotal
	}
	return nil
}

func (x *CartItem) GetPriceWhenAdded() *Price {
	if x != nil {
		return x.PriceWhenAdded
	}
	return nil
}

func (x *CartItem) GetOriginalPrice() *Price {
	if x != nil {
		return x.OriginalPrice
	}
	return nil
}

func (x *CartItem) GetCouponApplied() uint32 {
	if x != nil {
		return x.CouponApplied
	}
	return 0
}

func (x *CartItem) GetCouponDiscount() *Price {
	if x != nil {
		return x.CouponDiscount
	}
	return nil
}

func (x *CartItem) GetCanPurchaseAsGift() bool {
	if x != nil {
		return x.CanPurchaseAsGift
	}
	return false
}

func (x *CartItem) GetRestrictAddAdditionalToCart() bool {
	if x != nil {
		return x.RestrictAddAdditionalToCart
	}
	return false
}

// 商店信息
type StoreInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*ItemID              `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Context       *Context               `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	DataRequest   *ItemDataRequest       `protobuf:"bytes,3,opt,name=data_request,json=dataRequest,proto3" json:"data_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreInfo) Reset() {
	*x = StoreInfo{}
	mi := &file_cart_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInfo) ProtoMessage() {}

func (x *StoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInfo.ProtoReflect.Descriptor instead.
func (*StoreInfo) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{16}
}

func (x *StoreInfo) GetIds() []*ItemID {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *StoreInfo) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StoreInfo) GetDataRequest() *ItemDataRequest {
	if x != nil {
		return x.DataRequest
	}
	return nil
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"` //'schinese'
	Elanguage     int32                  `protobuf:"varint,2,opt,name=elanguage,proto3" json:"elanguage,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"` //'CN'
	SteamRealm    int32                  `protobuf:"varint,4,opt,name=steam_realm,json=steamRealm,proto3" json:"steam_realm,omitempty"`   //1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_cart_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{17}
}

func (x *Context) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Context) GetElanguage() int32 {
	if x != nil {
		return x.Elanguage
	}
	return 0
}

func (x *Context) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Context) GetSteamRealm() int32 {
	if x != nil {
		return x.SteamRealm
	}
	return 0
}

type ItemID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         uint32                 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Packageid     uint32                 `protobuf:"varint,2,opt,name=packageid,proto3" json:"packageid,omitempty"`
	Bundleid      uint32                 `protobuf:"varint,3,opt,name=bundleid,proto3" json:"bundleid,omitempty"`
	Tagid         uint32                 `protobuf:"varint,4,opt,name=tagid,proto3" json:"tagid,omitempty"`
	Creatorid     uint32                 `protobuf:"varint,5,opt,name=creatorid,proto3" json:"creatorid,omitempty"`
	Hubcategoryid uint32                 `protobuf:"varint,6,opt,name=hubcategoryid,proto3" json:"hubcategoryid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemID) Reset() {
	*x = ItemID{}
	mi := &file_cart_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemID) ProtoMessage() {}

func (x *ItemID) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemID.ProtoReflect.Descriptor instead.
func (*ItemID) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{18}
}

func (x *ItemID) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *ItemID) GetPackageid() uint32 {
	if x != nil {
		return x.Packageid
	}
	return 0
}

func (x *ItemID) GetBundleid() uint32 {
	if x != nil {
		return x.Bundleid
	}
	return 0
}

func (x *ItemID) GetTagid() uint32 {
	if x != nil {
		return x.Tagid
	}
	return 0
}

func (x *ItemID) GetCreatorid() uint32 {
	if x != nil {
		return x.Creatorid
	}
	return 0
}

func (x *ItemID) GetHubcategoryid() uint32 {
	if x != nil {
		return x.Hubcategoryid
	}
	return 0
}

type Estimate struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Subtotal               *Price                 `protobuf:"bytes,1,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	WalletBalance          *Price                 `protobuf:"bytes,2,opt,name=wallet_balance,json=walletBalance,proto3" json:"wallet_balance,omitempty"`
	ExceedingWalletBalance *Price                 `protobuf:"bytes,3,opt,name=exceeding_wallet_balance,json=exceedingWalletBalance,proto3" json:"exceeding_wallet_balance,omitempty"`
	RemainingWalletBalance *Price                 `protobuf:"bytes,4,opt,name=remaining_wallet_balance,json=remainingWalletBalance,proto3" json:"remaining_wallet_balance,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Estimate) Reset() {
	*x = Estimate{}
	mi := &file_cart_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Estimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estimate) ProtoMessage() {}

func (x *Estimate) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estimate.ProtoReflect.Descriptor instead.
func (*Estimate) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{19}
}

func (x *Estimate) GetSubtotal() *Price {
	if x != nil {
		return x.Subtotal
	}
	return nil
}

func (x *Estimate) GetWalletBalance() *Price {
	if x != nil {
		return x.WalletBalance
	}
	return nil
}

func (x *Estimate) GetExceedingWalletBalance() *Price {
	if x != nil {
		return x.ExceedingWalletBalance
	}
	return nil
}

func (x *Estimate) GetRemainingWalletBalance() *Price {
	if x != nil {
		return x.RemainingWalletBalance
	}
	return nil
}

// 删除消息发送
type RemoveCartSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineItemId    uint64                 `protobuf:"varint,1,opt,name=line_item_id,json=lineItemId,proto3" json:"line_item_id,omitempty"`
	UserCountry   string                 `protobuf:"bytes,2,opt,name=user_country,json=userCountry,proto3" json:"user_country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartSend) Reset() {
	*x = RemoveCartSend{}
	mi := &file_cart_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartSend) ProtoMessage() {}

func (x *RemoveCartSend) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartSend.ProtoReflect.Descriptor instead.
func (*RemoveCartSend) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveCartSend) GetLineItemId() uint64 {
	if x != nil {
		return x.LineItemId
	}
	return 0
}

func (x *RemoveCartSend) GetUserCountry() string {
	if x != nil {
		return x.UserCountry
	}
	return ""
}

type ItemDataRequest struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	IncludeAssets                 bool                   `protobuf:"varint,1,opt,name=include_assets,json=includeAssets,proto3" json:"include_assets,omitempty"`
	IncludeRelease                bool                   `protobuf:"varint,2,opt,name=include_release,json=includeRelease,proto3" json:"include_release,omitempty"`
	IncludePlatforms              bool                   `protobuf:"varint,3,opt,name=include_platforms,json=includePlatforms,proto3" json:"include_platforms,omitempty"`
	IncludeAllPurchaseOptions     bool                   `protobuf:"varint,4,opt,name=include_all_purchase_options,json=includeAllPurchaseOptions,proto3" json:"include_all_purchase_options,omitempty"`
	IncludeScreenshots            bool                   `protobuf:"varint,5,opt,name=include_screenshots,json=includeScreenshots,proto3" json:"include_screenshots,omitempty"`
	IncludeTrailers               bool                   `protobuf:"varint,6,opt,name=include_trailers,json=includeTrailers,proto3" json:"include_trailers,omitempty"`
	IncludeRatings                bool                   `protobuf:"varint,7,opt,name=include_ratings,json=includeRatings,proto3" json:"include_ratings,omitempty"`
	IncludeTagCount               int32                  `protobuf:"varint,8,opt,name=include_tag_count,json=includeTagCount,proto3" json:"include_tag_count,omitempty"`
	IncludeReviews                bool                   `protobuf:"varint,9,opt,name=include_reviews,json=includeReviews,proto3" json:"include_reviews,omitempty"`
	IncludeBasicInfo              bool                   `protobuf:"varint,10,opt,name=include_basic_info,json=includeBasicInfo,proto3" json:"include_basic_info,omitempty"`
	IncludeSupportedLanguages     bool                   `protobuf:"varint,11,opt,name=include_supported_languages,json=includeSupportedLanguages,proto3" json:"include_supported_languages,omitempty"`
	IncludeFullDescription        bool                   `protobuf:"varint,12,opt,name=include_full_description,json=includeFullDescription,proto3" json:"include_full_description,omitempty"`
	IncludeIncludedItems          bool                   `protobuf:"varint,13,opt,name=include_included_items,json=includeIncludedItems,proto3" json:"include_included_items,omitempty"`
	IncludedItemDataRequest       *ItemDataRequest       `protobuf:"bytes,14,opt,name=included_item_data_request,json=includedItemDataRequest,proto3" json:"included_item_data_request,omitempty"`
	IncludeAssetsWithoutOverrides bool                   `protobuf:"varint,15,opt,name=include_assets_without_overrides,json=includeAssetsWithoutOverrides,proto3" json:"include_assets_without_overrides,omitempty"`
	ApplyUserFilters              bool                   `protobuf:"varint,16,opt,name=apply_user_filters,json=applyUserFilters,proto3" json:"apply_user_filters,omitempty"`
	IncludeLinks                  bool                   `protobuf:"varint,17,opt,name=include_links,json=includeLinks,proto3" json:"include_links,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ItemDataRequest) Reset() {
	*x = ItemDataRequest{}
	mi := &file_cart_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDataRequest) ProtoMessage() {}

func (x *ItemDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDataRequest.ProtoReflect.Descriptor instead.
func (*ItemDataRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{21}
}

func (x *ItemDataRequest) GetIncludeAssets() bool {
	if x != nil {
		return x.IncludeAssets
	}
	return false
}

func (x *ItemDataRequest) GetIncludeRelease() bool {
	if x != nil {
		return x.IncludeRelease
	}
	return false
}

func (x *ItemDataRequest) GetIncludePlatforms() bool {
	if x != nil {
		return x.IncludePlatforms
	}
	return false
}

func (x *ItemDataRequest) GetIncludeAllPurchaseOptions() bool {
	if x != nil {
		return x.IncludeAllPurchaseOptions
	}
	return false
}

func (x *ItemDataRequest) GetIncludeScreenshots() bool {
	if x != nil {
		return x.IncludeScreenshots
	}
	return false
}

func (x *ItemDataRequest) GetIncludeTrailers() bool {
	if x != nil {
		return x.IncludeTrailers
	}
	return false
}

func (x *ItemDataRequest) GetIncludeRatings() bool {
	if x != nil {
		return x.IncludeRatings
	}
	return false
}

func (x *ItemDataRequest) GetIncludeTagCount() int32 {
	if x != nil {
		return x.IncludeTagCount
	}
	return 0
}

func (x *ItemDataRequest) GetIncludeReviews() bool {
	if x != nil {
		return x.IncludeReviews
	}
	return false
}

func (x *ItemDataRequest) GetIncludeBasicInfo() bool {
	if x != nil {
		return x.IncludeBasicInfo
	}
	return false
}

func (x *ItemDataRequest) GetIncludeSupportedLanguages() bool {
	if x != nil {
		return x.IncludeSupportedLanguages
	}
	return false
}

func (x *ItemDataRequest) GetIncludeFullDescription() bool {
	if x != nil {
		return x.IncludeFullDescription
	}
	return false
}

func (x *ItemDataRequest) GetIncludeIncludedItems() bool {
	if x != nil {
		return x.IncludeIncludedItems
	}
	return false
}

func (x *ItemDataRequest) GetIncludedItemDataRequest() *ItemDataRequest {
	if x != nil {
		return x.IncludedItemDataRequest
	}
	return nil
}

func (x *ItemDataRequest) GetIncludeAssetsWithoutOverrides() bool {
	if x != nil {
		return x.IncludeAssetsWithoutOverrides
	}
	return false
}

func (x *ItemDataRequest) GetApplyUserFilters() bool {
	if x != nil {
		return x.ApplyUserFilters
	}
	return false
}

func (x *ItemDataRequest) GetIncludeLinks() bool {
	if x != nil {
		return x.IncludeLinks
	}
	return false
}

type RemoveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineItemId    uint64                 `protobuf:"varint,1,opt,name=line_item_id,json=lineItemId,proto3" json:"line_item_id,omitempty"`
	UserCountry   string                 `protobuf:"bytes,2,opt,name=user_country,json=userCountry,proto3" json:"user_country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItem) Reset() {
	*x = RemoveItem{}
	mi := &file_cart_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItem) ProtoMessage() {}

func (x *RemoveItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItem.ProtoReflect.Descriptor instead.
func (*RemoveItem) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveItem) GetLineItemId() uint64 {
	if x != nil {
		return x.LineItemId
	}
	return 0
}

func (x *RemoveItem) GetUserCountry() string {
	if x != nil {
		return x.UserCountry
	}
	return ""
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x12\x05steam\x1a\vstore.proto\"}\n" +
	"\vAddCartSend\x12!\n" +
	"\fuser_country\x18\x01 \x01(\tR\vuserCountry\x12!\n" +
	"\x05items\x18\x02 \x03(\v2\v.steam.ItemR\x05items\x12(\n" +
	"\anavdata\x18\x03 \x01(\v2\x0e.steam.NavdataR\anavdata\"\x8f\x01\n" +
	"\x04Item\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\rR\tpackageid\x12\x1a\n" +
	"\bbundleid\x18\x02 \x01(\rR\bbundleid\x12,\n" +
	"\tgift_info\x18\n" +
	" \x01(\v2\x0f.steam.GiftInfoR\bgiftInfo\x12\x1f\n" +
	"\x04flag\x18\v \x01(\v2\v.steam.FlagR\x04flag\"=\n" +
	"\vCuratorData\x12\x16\n" +
	"\x06clanid\x18\x01 \x01(\rR\x06clanid\x12\x16\n" +
	"\x06listid\x18\x02 \x01(\x04R\x06listid\"\xf0\x02\n" +
	"\aNavdata\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1e\n" +
	"\n" +
	"controller\x18\x02 \x01(\tR\n" +
	"controller\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1c\n" +
	"\tsubmethod\x18\x04 \x01(\tR\tsubmethod\x12\x18\n" +
	"\afeature\x18\x05 \x01(\tR\afeature\x12\x14\n" +
	"\x05depth\x18\x06 \x01(\rR\x05depth\x12 \n" +
	"\vcountrycode\x18\a \x01(\tR\vcountrycode\x12\x16\n" +
	"\x06webkey\x18\b \x01(\tR\x06webkey\x12\x1b\n" +
	"\tis_client\x18\t \x01(\bR\bisClient\x125\n" +
	"\fcurator_data\x18\n" +
	" \x01(\v2\x12.steam.CuratorDataR\vcuratorData\x12\"\n" +
	"\ris_likely_bot\x18\v \x01(\bR\visLikelyBot\x12\x15\n" +
	"\x06is_utm\x18\f \x01(\bR\x05isUtm\"\x9c\x01\n" +
	"\bGiftInfo\x12)\n" +
	"\x10accountid_giftee\x18\x01 \x01(\x05R\x0faccountidGiftee\x125\n" +
	"\fgift_message\x18\x02 \x01(\v2\x12.steam.GiftMessageR\vgiftMessage\x12.\n" +
	"\x13time_scheduled_send\x18\x03 \x01(\x05R\x11timeScheduledSend\"\x83\x01\n" +
	"\vGiftMessage\x12\x1e\n" +
	"\n" +
	"gifteename\x18\x01 \x01(\tR\n" +
	"gifteename\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tsentiment\x18\x03 \x01(\tR\tsentiment\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\">\n" +
	"\x04Flag\x12\x17\n" +
	"\ais_gift\x18\x01 \x01(\bR\x06isGift\x12\x1d\n" +
	"\n" +
	"is_private\x18\x02 \x01(\bR\tisPrivate\"\x9e\x02\n" +
	"\x0eAddCartReceive\x12\"\n" +
	"\rline_item_ids\x18\x01 \x03(\x04R\vlineItemIds\x12\x1f\n" +
	"\x04cart\x18\x02 \x01(\v2\v.steam.CartR\x04cart\x12+\n" +
	"\x11replaced_packages\x18\x03 \x03(\rR\x10replacedPackages\x12@\n" +
	"\x1cexisting_billing_agreementid\x18\x04 \x01(\x04R\x1aexistingBillingAgreementid\x12X\n" +
	")new_billing_agreement_recurring_packageid\x18\x05 \x01(\rR%newBillingAgreementRecurringPackageid\"\xcd\x01\n" +
	"\x0eModifyCartSend\x12 \n" +
	"\fline_item_id\x18\x01 \x01(\x04R\n" +
	"lineItemId\x12!\n" +
	"\fuser_country\x18\x02 \x01(\tR\vuserCountry\x12,\n" +
	"\tgift_info\x18\n" +
	" \x01(\v2\x0f.steam.GiftInfoR\bgiftInfo\x12\x1f\n" +
	"\x04flag\x18\v \x01(\v2\v.steam.FlagR\x04flag\x12'\n" +
	"\x0fapply_gidcoupon\x18\f \x01(\x04R\x0eapplyGidcoupon\"4\n" +
	"\x11ModifyCartReceive\x12\x1f\n" +
	"\x04cart\x18\x01 \x01(\v2\v.steam.CartR\x04cart\"\xc4\x01\n" +
	"\x04Cart\x12.\n" +
	"\n" +
	"line_items\x18\x01 \x03(\v2\x0f.steam.LineItemR\tlineItems\x12(\n" +
	"\bsubtotal\x18\x02 \x03(\v2\f.steam.PriceR\bsubtotal\x12\x19\n" +
	"\bis_valid\x18\x03 \x01(\bR\aisValid\x12G\n" +
	"\x12validation_details\x18\x04 \x03(\v2\x18.steam.ValidationFailureR\x11validationDetails\"\xb1\x03\n" +
	"\bLineItem\x12 \n" +
	"\fline_item_id\x18\x01 \x01(\x04R\n" +
	"lineItemId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x1c\n" +
	"\tpackageid\x18\x03 \x01(\rR\tpackageid\x12\x1a\n" +
	"\bbundleid\x18\x04 \x01(\rR\bbundleid\x12\x19\n" +
	"\bis_valid\x18\b \x01(\bR\aisValid\x12G\n" +
	"\x12validation_details\x18\t \x01(\v2\x18.steam.ValidationFailureR\x11validationDetails\x12\x1d\n" +
	"\n" +
	"time_added\x18\n" +
	" \x01(\rR\ttimeAdded\x126\n" +
	"\x10price_when_added\x18\v \x01(\v2\f.steam.PriceR\x0epriceWhenAdded\x12,\n" +
	"\tgift_info\x18\f \x01(\v2\x0f.steam.GiftInfoR\bgiftInfo\x12\x1f\n" +
	"\x04flag\x18\r \x01(\v2\v.steam.FlagR\x04flag\x12+\n" +
	"\x11gidcoupon_applied\x18\x0e \x01(\x04R\x10gidcouponApplied\"B\n" +
	"\x11ValidationFailure\x12-\n" +
	"\x12validation_failure\x18\x01 \x01(\rR\x11validationFailure\"\x7f\n" +
	"\x05Price\x12&\n" +
	"\x0famount_in_cents\x18\x01 \x01(\x03R\ramountInCents\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\x05R\fcurrencyCode\x12)\n" +
	"\x10formatted_amount\x18\x03 \x01(\tR\x0fformattedAmount\"v\n" +
	"\bCartInfo\x12.\n" +
	"\n" +
	"cart_items\x18\x01 \x03(\v2\x0f.steam.CartItemR\tcartItems\x12:\n" +
	"\x10estimated_totals\x18\x05 \x03(\v2\x0f.steam.EstimateR\x0festimatedTotals\"\xd3\x04\n" +
	"\bCartItem\x12 \n" +
	"\fline_item_id\x18\x01 \x01(\x04R\n" +
	"lineItemId\x12&\n" +
	"\aitem_id\x18\x02 \x01(\v2\r.steam.ItemIDR\x06itemId\x12/\n" +
	"\n" +
	"store_item\x18\x03 \x01(\v2\x10.steam.StoreItemR\tstoreItem\x12,\n" +
	"\tgift_info\x18\x04 \x01(\v2\x0f.steam.GiftInfoR\bgiftInfo\x12\x16\n" +
	"\x06errors\x18\x05 \x01(\rR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x06 \x01(\rR\bwarnings\x12(\n" +
	"\bsubtotal\x18\a \x01(\v2\f.steam.PriceR\bsubtotal\x126\n" +
	"\x10price_when_added\x18\b \x01(\v2\f.steam.PriceR\x0epriceWhenAdded\x123\n" +
	"\x0eoriginal_price\x18\t \x01(\v2\f.steam.PriceR\roriginalPrice\x12%\n" +
	"\x0ecoupon_applied\x18\n" +
	" \x01(\rR\rcouponApplied\x125\n" +
	"\x0fcoupon_discount\x18\v \x01(\v2\f.steam.PriceR\x0ecouponDiscount\x12/\n" +
	"\x14can_purchase_as_gift\x18\f \x01(\bR\x11canPurchaseAsGift\x12D\n" +
	"\x1frestrict_add_additional_to_cart\x18\r \x01(\bR\x1brestrictAddAdditionalToCart\"\x91\x01\n" +
	"\tStoreInfo\x12\x1f\n" +
	"\x03ids\x18\x01 \x03(\v2\r.steam.ItemIDR\x03ids\x12(\n" +
	"\acontext\x18\x02 \x01(\v2\x0e.steam.ContextR\acontext\x129\n" +
	"\fdata_request\x18\x03 \x01(\v2\x16.steam.ItemDataRequestR\vdataRequest\"\x87\x01\n" +
	"\aContext\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1c\n" +
	"\telanguage\x18\x02 \x01(\x05R\telanguage\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12\x1f\n" +
	"\vsteam_realm\x18\x04 \x01(\x05R\n" +
	"steamRealm\"\xb2\x01\n" +
	"\x06ItemID\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1c\n" +
	"\tpackageid\x18\x02 \x01(\rR\tpackageid\x12\x1a\n" +
	"\bbundleid\x18\x03 \x01(\rR\bbundleid\x12\x14\n" +
	"\x05tagid\x18\x04 \x01(\rR\x05tagid\x12\x1c\n" +
	"\tcreatorid\x18\x05 \x01(\rR\tcreatorid\x12$\n" +
	"\rhubcategoryid\x18\x06 \x01(\rR\rhubcategoryid\"\xf9\x01\n" +
	"\bEstimate\x12(\n" +
	"\bsubtotal\x18\x01 \x01(\v2\f.steam.PriceR\bsubtotal\x123\n" +
	"\x0ewallet_balance\x18\x02 \x01(\v2\f.steam.PriceR\rwalletBalance\x12F\n" +
	"\x18exceeding_wallet_balance\x18\x03 \x01(\v2\f.steam.PriceR\x16exceedingWalletBalance\x12F\n" +
	"\x18remaining_wallet_balance\x18\x04 \x01(\v2\f.steam.PriceR\x16remainingWalletBalance\"U\n" +
	"\x0eRemoveCartSend\x12 \n" +
	"\fline_item_id\x18\x01 \x01(\x04R\n" +
	"lineItemId\x12!\n" +
	"\fuser_country\x18\x02 \x01(\tR\vuserCountry\"\xf8\x06\n" +
	"\x0fItemDataRequest\x12%\n" +
	"\x0einclude_assets\x18\x01 \x01(\bR\rincludeAssets\x12'\n" +
	"\x0finclude_release\x18\x02 \x01(\bR\x0eincludeRelease\x12+\n" +
	"\x11include_platforms\x18\x03 \x01(\bR\x10includePlatforms\x12?\n" +
	"\x1cinclude_all_purchase_options\x18\x04 \x01(\bR\x19includeAllPurchaseOptions\x12/\n" +
	"\x13include_screenshots\x18\x05 \x01(\bR\x12includeScreenshots\x12)\n" +
	"\x10include_trailers\x18\x06 \x01(\bR\x0fincludeTrailers\x12'\n" +
	"\x0finclude_ratings\x18\a \x01(\bR\x0eincludeRatings\x12*\n" +
	"\x11include_tag_count\x18\b \x01(\x05R\x0fincludeTagCount\x12'\n" +
	"\x0finclude_reviews\x18\t \x01(\bR\x0eincludeReviews\x12,\n" +
	"\x12include_basic_info\x18\n" +
	" \x01(\bR\x10includeBasicInfo\x12>\n" +
	"\x1binclude_supported_languages\x18\v \x01(\bR\x19includeSupportedLanguages\x128\n" +
	"\x18include_full_description\x18\f \x01(\bR\x16includeFullDescription\x124\n" +
	"\x16include_included_items\x18\r \x01(\bR\x14includeIncludedItems\x12S\n" +
	"\x1aincluded_item_data_request\x18\x0e \x01(\v2\x16.steam.ItemDataRequestR\x17includedItemDataRequest\x12G\n" +
	" include_assets_without_overrides\x18\x0f \x01(\bR\x1dincludeAssetsWithoutOverrides\x12,\n" +
	"\x12apply_user_filters\x18\x10 \x01(\bR\x10applyUserFilters\x12#\n" +
	"\rinclude_links\x18\x11 \x01(\bR\fincludeLinks\"Q\n" +
	"\n" +
	"RemoveItem\x12 \n" +
	"\fline_item_id\x18\x01 \x01(\x04R\n" +
	"lineItemId\x12!\n" +
	"\fuser_country\x18\x02 \x01(\tR\vuserCountryB\vZ\t../Protocb\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cart_proto_goTypes = []any{
	(*AddCartSend)(nil),       // 0: steam.AddCartSend
	(*Item)(nil),              // 1: steam.Item
	(*CuratorData)(nil),       // 2: steam.CuratorData
	(*Navdata)(nil),           // 3: steam.Navdata
	(*GiftInfo)(nil),          // 4: steam.GiftInfo
	(*GiftMessage)(nil),       // 5: steam.GiftMessage
	(*Flag)(nil),              // 6: steam.Flag
	(*AddCartReceive)(nil),    // 7: steam.AddCartReceive
	(*ModifyCartSend)(nil),    // 8: steam.ModifyCartSend
	(*ModifyCartReceive)(nil), // 9: steam.ModifyCartReceive
	(*Cart)(nil),              // 10: steam.Cart
	(*LineItem)(nil),          // 11: steam.LineItem
	(*ValidationFailure)(nil), // 12: steam.ValidationFailure
	(*Price)(nil),             // 13: steam.Price
	(*CartInfo)(nil),          // 14: steam.CartInfo
	(*CartItem)(nil),          // 15: steam.CartItem
	(*StoreInfo)(nil),         // 16: steam.StoreInfo
	(*Context)(nil),           // 17: steam.Context
	(*ItemID)(nil),            // 18: steam.ItemID
	(*Estimate)(nil),          // 19: steam.Estimate
	(*RemoveCartSend)(nil),    // 20: steam.RemoveCartSend
	(*ItemDataRequest)(nil),   // 21: steam.ItemDataRequest
	(*RemoveItem)(nil),        // 22: steam.RemoveItem
	(*StoreItem)(nil),         // 23: steam.StoreItem
}
var file_cart_proto_depIdxs = []int32{
	1,  // 0: steam.AddCartSend.items:type_name -> steam.Item
	3,  // 1: steam.AddCartSend.navdata:type_name -> steam.Navdata
	4,  // 2: steam.Item.gift_info:type_name -> steam.GiftInfo
	6,  // 3: steam.Item.flag:type_name -> steam.Flag
	2,  // 4: steam.Navdata.curator_data:type_name -> steam.CuratorData
	5,  // 5: steam.GiftInfo.gift_message:type_name -> steam.GiftMessage
	10, // 6: steam.AddCartReceive.cart:type_name -> steam.Cart
	4,  // 7: steam.ModifyCartSend.gift_info:type_name -> steam.GiftInfo
	6,  // 8: steam.ModifyCartSend.flag:type_name -> steam.Flag
	10, // 9: steam.ModifyCartReceive.cart:type_name -> steam.Cart
	11, // 10: steam.Cart.line_items:type_name -> steam.LineItem
	13, // 11: steam.Cart.subtotal:type_name -> steam.Price
	12, // 12: steam.Cart.validation_details:type_name -> steam.ValidationFailure
	12, // 13: steam.LineItem.validation_details:type_name -> steam.ValidationFailure
	13, // 14: steam.LineItem.price_when_added:type_name -> steam.Price
	4,  // 15: steam.LineItem.gift_info:type_name -> steam.GiftInfo
	6,  // 16: steam.LineItem.flag:type_name -> steam.Flag
	15, // 17: steam.CartInfo.cart_items:type_name -> steam.CartItem
	19, // 18: steam.CartInfo.estimated_totals:type_name -> steam.Estimate
	18, // 19: steam.CartItem.item_id:type_name -> steam.ItemID
	23, // 20: steam.CartItem.store_item:type_name -> steam.StoreItem
	4,  // 21: steam.CartItem.gift_info:type_name -> steam.GiftInfo
	13, // 22: steam.CartItem.subtotal:type_name -> steam.Price
	13, // 23: steam.CartItem.price_when_added:type_name -> steam.Price
	13, // 24: steam.CartItem.original_price:type_name -> steam.Price
	13, // 25: steam.CartItem.coupon_discount:type_name -> steam.Price
	18, // 26: steam.StoreInfo.ids:type_name -> steam.ItemID
	17, // 27: steam.StoreInfo.context:type_name -> steam.Context
	21, // 28: steam.StoreInfo.data_request:type_name -> steam.ItemDataRequest
	13, // 29: steam.Estimate.subtotal:type_name -> steam.Price
	13, // 30: steam.Estimate.wallet_balance:type_name -> steam.Price
	13, // 31: steam.Estimate.exceeding_wallet_balance:type_name -> steam.Price
	13, // 32: steam.Estimate.remaining_wallet_balance:type_name -> steam.Price
	21, // 33: steam.ItemDataRequest.included_item_data_request:type_name -> steam.ItemDataRequest
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	file_store_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
