// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.2
// source: login.proto

package Protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPasswordRSAPublicKeySend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"` //steam账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasswordRSAPublicKeySend) Reset() {
	*x = GetPasswordRSAPublicKeySend{}
	mi := &file_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasswordRSAPublicKeySend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasswordRSAPublicKeySend) ProtoMessage() {}

func (x *GetPasswordRSAPublicKeySend) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasswordRSAPublicKeySend.ProtoReflect.Descriptor instead.
func (*GetPasswordRSAPublicKeySend) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *GetPasswordRSAPublicKeySend) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type GetPasswordRSAPublicKeySendReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublickeyMod  string                 `protobuf:"bytes,1,opt,name=publickey_mod,json=publickeyMod,proto3" json:"publickey_mod,omitempty"`
	PublickeyExp  string                 `protobuf:"bytes,2,opt,name=publickey_exp,json=publickeyExp,proto3" json:"publickey_exp,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasswordRSAPublicKeySendReceive) Reset() {
	*x = GetPasswordRSAPublicKeySendReceive{}
	mi := &file_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasswordRSAPublicKeySendReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasswordRSAPublicKeySendReceive) ProtoMessage() {}

func (x *GetPasswordRSAPublicKeySendReceive) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasswordRSAPublicKeySendReceive.ProtoReflect.Descriptor instead.
func (*GetPasswordRSAPublicKeySendReceive) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *GetPasswordRSAPublicKeySendReceive) GetPublickeyMod() string {
	if x != nil {
		return x.PublickeyMod
	}
	return ""
}

func (x *GetPasswordRSAPublicKeySendReceive) GetPublickeyExp() string {
	if x != nil {
		return x.PublickeyExp
	}
	return ""
}

func (x *GetPasswordRSAPublicKeySendReceive) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DeviceDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceFriendlyName string                 `protobuf:"bytes,1,opt,name=device_friendly_name,json=deviceFriendlyName,proto3" json:"device_friendly_name,omitempty"`
	PlatformType       int32                  `protobuf:"varint,2,opt,name=platform_type,json=platformType,proto3" json:"platform_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceDetails) Reset() {
	*x = DeviceDetails{}
	mi := &file_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDetails) ProtoMessage() {}

func (x *DeviceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDetails.ProtoReflect.Descriptor instead.
func (*DeviceDetails) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceDetails) GetDeviceFriendlyName() string {
	if x != nil {
		return x.DeviceFriendlyName
	}
	return ""
}

func (x *DeviceDetails) GetPlatformType() int32 {
	if x != nil {
		return x.PlatformType
	}
	return 0
}

type BeginAuthSessionViaCredentialsSend struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FriendlyName        string                 `protobuf:"bytes,1,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	AccountName         string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	EncryptedPassword   string                 `protobuf:"bytes,3,opt,name=encrypted_password,json=encryptedPassword,proto3" json:"encrypted_password,omitempty"`
	EncryptionTimestamp int64                  `protobuf:"varint,4,opt,name=encryption_timestamp,json=encryptionTimestamp,proto3" json:"encryption_timestamp,omitempty"` // unit64string
	RememberLogin       bool                   `protobuf:"varint,5,opt,name=remember_login,json=rememberLogin,proto3" json:"remember_login,omitempty"`
	PlatformType        int32                  `protobuf:"varint,6,opt,name=platform_type,json=platformType,proto3" json:"platform_type,omitempty"` //enum
	Persistence         int32                  `protobuf:"varint,7,opt,name=persistence,proto3" json:"persistence,omitempty"`                       //enum
	WebsiteId           string                 `protobuf:"bytes,8,opt,name=website_id,json=websiteId,proto3" json:"website_id,omitempty"`
	DeviceDetails       *DeviceDetails         `protobuf:"bytes,9,opt,name=device_details,json=deviceDetails,proto3" json:"device_details,omitempty"`
	GuardData           int32                  `protobuf:"varint,10,opt,name=guard_data,json=guardData,proto3" json:"guard_data,omitempty"`
	Language            int32                  `protobuf:"varint,11,opt,name=language,proto3" json:"language,omitempty"`
	QosLevel            int32                  `protobuf:"varint,12,opt,name=qos_level,json=qosLevel,proto3" json:"qos_level,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BeginAuthSessionViaCredentialsSend) Reset() {
	*x = BeginAuthSessionViaCredentialsSend{}
	mi := &file_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthSessionViaCredentialsSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthSessionViaCredentialsSend) ProtoMessage() {}

func (x *BeginAuthSessionViaCredentialsSend) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthSessionViaCredentialsSend.ProtoReflect.Descriptor instead.
func (*BeginAuthSessionViaCredentialsSend) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{3}
}

func (x *BeginAuthSessionViaCredentialsSend) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *BeginAuthSessionViaCredentialsSend) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BeginAuthSessionViaCredentialsSend) GetEncryptedPassword() string {
	if x != nil {
		return x.EncryptedPassword
	}
	return ""
}

func (x *BeginAuthSessionViaCredentialsSend) GetEncryptionTimestamp() int64 {
	if x != nil {
		return x.EncryptionTimestamp
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsSend) GetRememberLogin() bool {
	if x != nil {
		return x.RememberLogin
	}
	return false
}

func (x *BeginAuthSessionViaCredentialsSend) GetPlatformType() int32 {
	if x != nil {
		return x.PlatformType
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsSend) GetPersistence() int32 {
	if x != nil {
		return x.Persistence
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsSend) GetWebsiteId() string {
	if x != nil {
		return x.WebsiteId
	}
	return ""
}

func (x *BeginAuthSessionViaCredentialsSend) GetDeviceDetails() *DeviceDetails {
	if x != nil {
		return x.DeviceDetails
	}
	return nil
}

func (x *BeginAuthSessionViaCredentialsSend) GetGuardData() int32 {
	if x != nil {
		return x.GuardData
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsSend) GetLanguage() int32 {
	if x != nil {
		return x.Language
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsSend) GetQosLevel() int32 {
	if x != nil {
		return x.QosLevel
	}
	return 0
}

type Confirmation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationType  int32                  `protobuf:"varint,1,opt,name=confirmation_type,json=confirmationType,proto3" json:"confirmation_type,omitempty"`
	AssociatedMessage string                 `protobuf:"bytes,2,opt,name=associated_message,json=associatedMessage,proto3" json:"associated_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	mi := &file_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{4}
}

func (x *Confirmation) GetConfirmationType() int32 {
	if x != nil {
		return x.ConfirmationType
	}
	return 0
}

func (x *Confirmation) GetAssociatedMessage() string {
	if x != nil {
		return x.AssociatedMessage
	}
	return ""
}

type BeginAuthSessionViaCredentialsReceive struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientId             uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId            []byte                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Interval             float32                `protobuf:"fixed32,3,opt,name=interval,proto3" json:"interval,omitempty"`
	AllowedConfirmations []*Confirmation        `protobuf:"bytes,4,rep,name=allowed_confirmations,json=allowedConfirmations,proto3" json:"allowed_confirmations,omitempty"`
	SteamId              uint64                 `protobuf:"varint,5,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	WeakToken            string                 `protobuf:"bytes,6,opt,name=weak_token,json=weakToken,proto3" json:"weak_token,omitempty"`
	AgreementSessionUrl  string                 `protobuf:"bytes,7,opt,name=agreement_session_url,json=agreementSessionUrl,proto3" json:"agreement_session_url,omitempty"`
	ExtendedErrorMessage string                 `protobuf:"bytes,8,opt,name=extended_error_message,json=extendedErrorMessage,proto3" json:"extended_error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BeginAuthSessionViaCredentialsReceive) Reset() {
	*x = BeginAuthSessionViaCredentialsReceive{}
	mi := &file_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthSessionViaCredentialsReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthSessionViaCredentialsReceive) ProtoMessage() {}

func (x *BeginAuthSessionViaCredentialsReceive) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthSessionViaCredentialsReceive.ProtoReflect.Descriptor instead.
func (*BeginAuthSessionViaCredentialsReceive) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{5}
}

func (x *BeginAuthSessionViaCredentialsReceive) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsReceive) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *BeginAuthSessionViaCredentialsReceive) GetInterval() float32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsReceive) GetAllowedConfirmations() []*Confirmation {
	if x != nil {
		return x.AllowedConfirmations
	}
	return nil
}

func (x *BeginAuthSessionViaCredentialsReceive) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *BeginAuthSessionViaCredentialsReceive) GetWeakToken() string {
	if x != nil {
		return x.WeakToken
	}
	return ""
}

func (x *BeginAuthSessionViaCredentialsReceive) GetAgreementSessionUrl() string {
	if x != nil {
		return x.AgreementSessionUrl
	}
	return ""
}

func (x *BeginAuthSessionViaCredentialsReceive) GetExtendedErrorMessage() string {
	if x != nil {
		return x.ExtendedErrorMessage
	}
	return ""
}

type PollAuthSessionStatusSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     []byte                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TokenToRevoke uint64                 `protobuf:"fixed64,3,opt,name=token_to_revoke,json=tokenToRevoke,proto3" json:"token_to_revoke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollAuthSessionStatusSend) Reset() {
	*x = PollAuthSessionStatusSend{}
	mi := &file_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollAuthSessionStatusSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAuthSessionStatusSend) ProtoMessage() {}

func (x *PollAuthSessionStatusSend) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAuthSessionStatusSend.ProtoReflect.Descriptor instead.
func (*PollAuthSessionStatusSend) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{6}
}

func (x *PollAuthSessionStatusSend) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PollAuthSessionStatusSend) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *PollAuthSessionStatusSend) GetTokenToRevoke() uint64 {
	if x != nil {
		return x.TokenToRevoke
	}
	return 0
}

type PollAuthSessionStatusReceive struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NewClientId          uint64                 `protobuf:"varint,1,opt,name=new_client_id,json=newClientId,proto3" json:"new_client_id,omitempty"`
	NewChallengeUrl      string                 `protobuf:"bytes,2,opt,name=new_challenge_url,json=newChallengeUrl,proto3" json:"new_challenge_url,omitempty"`
	RefreshToken         string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessToken          string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	HadRemoteInteraction bool                   `protobuf:"varint,5,opt,name=had_remote_interaction,json=hadRemoteInteraction,proto3" json:"had_remote_interaction,omitempty"`
	AccountName          string                 `protobuf:"bytes,6,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	NewGuardData         string                 `protobuf:"bytes,7,opt,name=new_guard_data,json=newGuardData,proto3" json:"new_guard_data,omitempty"`
	AgreementSessionUrl  string                 `protobuf:"bytes,8,opt,name=agreement_session_url,json=agreementSessionUrl,proto3" json:"agreement_session_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PollAuthSessionStatusReceive) Reset() {
	*x = PollAuthSessionStatusReceive{}
	mi := &file_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollAuthSessionStatusReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAuthSessionStatusReceive) ProtoMessage() {}

func (x *PollAuthSessionStatusReceive) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAuthSessionStatusReceive.ProtoReflect.Descriptor instead.
func (*PollAuthSessionStatusReceive) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{7}
}

func (x *PollAuthSessionStatusReceive) GetNewClientId() uint64 {
	if x != nil {
		return x.NewClientId
	}
	return 0
}

func (x *PollAuthSessionStatusReceive) GetNewChallengeUrl() string {
	if x != nil {
		return x.NewChallengeUrl
	}
	return ""
}

func (x *PollAuthSessionStatusReceive) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *PollAuthSessionStatusReceive) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *PollAuthSessionStatusReceive) GetHadRemoteInteraction() bool {
	if x != nil {
		return x.HadRemoteInteraction
	}
	return false
}

func (x *PollAuthSessionStatusReceive) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *PollAuthSessionStatusReceive) GetNewGuardData() string {
	if x != nil {
		return x.NewGuardData
	}
	return ""
}

func (x *PollAuthSessionStatusReceive) GetAgreementSessionUrl() string {
	if x != nil {
		return x.AgreementSessionUrl
	}
	return ""
}

type EmailCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Steamid       uint64                 `protobuf:"fixed64,2,opt,name=steamid,proto3" json:"steamid,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CodeType      int32                  `protobuf:"varint,4,opt,name=code_type,json=codeType,proto3" json:"code_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailCode) Reset() {
	*x = EmailCode{}
	mi := &file_login_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCode) ProtoMessage() {}

func (x *EmailCode) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCode.ProtoReflect.Descriptor instead.
func (*EmailCode) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{8}
}

func (x *EmailCode) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *EmailCode) GetSteamid() uint64 {
	if x != nil {
		return x.Steamid
	}
	return 0
}

func (x *EmailCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EmailCode) GetCodeType() int32 {
	if x != nil {
		return x.CodeType
	}
	return 0
}

var File_login_proto protoreflect.FileDescriptor

const file_login_proto_rawDesc = "" +
	"\n" +
	"\vlogin.proto\x12\x05steam\"@\n" +
	"\x1bGetPasswordRSAPublicKeySend\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\"\x8c\x01\n" +
	"\"GetPasswordRSAPublicKeySendReceive\x12#\n" +
	"\rpublickey_mod\x18\x01 \x01(\tR\fpublickeyMod\x12#\n" +
	"\rpublickey_exp\x18\x02 \x01(\tR\fpublickeyExp\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"f\n" +
	"\rDeviceDetails\x120\n" +
	"\x14device_friendly_name\x18\x01 \x01(\tR\x12deviceFriendlyName\x12#\n" +
	"\rplatform_type\x18\x02 \x01(\x05R\fplatformType\"\xf0\x03\n" +
	"\"BeginAuthSessionViaCredentialsSend\x12#\n" +
	"\rfriendly_name\x18\x01 \x01(\tR\ffriendlyName\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12-\n" +
	"\x12encrypted_password\x18\x03 \x01(\tR\x11encryptedPassword\x121\n" +
	"\x14encryption_timestamp\x18\x04 \x01(\x03R\x13encryptionTimestamp\x12%\n" +
	"\x0eremember_login\x18\x05 \x01(\bR\rrememberLogin\x12#\n" +
	"\rplatform_type\x18\x06 \x01(\x05R\fplatformType\x12 \n" +
	"\vpersistence\x18\a \x01(\x05R\vpersistence\x12\x1d\n" +
	"\n" +
	"website_id\x18\b \x01(\tR\twebsiteId\x12;\n" +
	"\x0edevice_details\x18\t \x01(\v2\x14.steam.DeviceDetailsR\rdeviceDetails\x12\x1d\n" +
	"\n" +
	"guard_data\x18\n" +
	" \x01(\x05R\tguardData\x12\x1a\n" +
	"\blanguage\x18\v \x01(\x05R\blanguage\x12\x1b\n" +
	"\tqos_level\x18\f \x01(\x05R\bqosLevel\"j\n" +
	"\fConfirmation\x12+\n" +
	"\x11confirmation_type\x18\x01 \x01(\x05R\x10confirmationType\x12-\n" +
	"\x12associated_message\x18\x02 \x01(\tR\x11associatedMessage\"\xed\x02\n" +
	"%BeginAuthSessionViaCredentialsReceive\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\fR\trequestId\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\x02R\binterval\x12H\n" +
	"\x15allowed_confirmations\x18\x04 \x03(\v2\x13.steam.ConfirmationR\x14allowedConfirmations\x12\x19\n" +
	"\bsteam_id\x18\x05 \x01(\x04R\asteamId\x12\x1d\n" +
	"\n" +
	"weak_token\x18\x06 \x01(\tR\tweakToken\x122\n" +
	"\x15agreement_session_url\x18\a \x01(\tR\x13agreementSessionUrl\x124\n" +
	"\x16extended_error_message\x18\b \x01(\tR\x14extendedErrorMessage\"\x7f\n" +
	"\x19PollAuthSessionStatusSend\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\fR\trequestId\x12&\n" +
	"\x0ftoken_to_revoke\x18\x03 \x01(\x06R\rtokenToRevoke\"\xe9\x02\n" +
	"\x1cPollAuthSessionStatusReceive\x12\"\n" +
	"\rnew_client_id\x18\x01 \x01(\x04R\vnewClientId\x12*\n" +
	"\x11new_challenge_url\x18\x02 \x01(\tR\x0fnewChallengeUrl\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x124\n" +
	"\x16had_remote_interaction\x18\x05 \x01(\bR\x14hadRemoteInteraction\x12!\n" +
	"\faccount_name\x18\x06 \x01(\tR\vaccountName\x12$\n" +
	"\x0enew_guard_data\x18\a \x01(\tR\fnewGuardData\x122\n" +
	"\x15agreement_session_url\x18\b \x01(\tR\x13agreementSessionUrl\"s\n" +
	"\tEmailCode\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x18\n" +
	"\asteamid\x18\x02 \x01(\x06R\asteamid\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tcode_type\x18\x04 \x01(\x05R\bcodeTypeB\vZ\t../Protocb\x06proto3"

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData []byte
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)))
	})
	return file_login_proto_rawDescData
}

var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_login_proto_goTypes = []any{
	(*GetPasswordRSAPublicKeySend)(nil),           // 0: steam.GetPasswordRSAPublicKeySend
	(*GetPasswordRSAPublicKeySendReceive)(nil),    // 1: steam.GetPasswordRSAPublicKeySendReceive
	(*DeviceDetails)(nil),                         // 2: steam.DeviceDetails
	(*BeginAuthSessionViaCredentialsSend)(nil),    // 3: steam.BeginAuthSessionViaCredentialsSend
	(*Confirmation)(nil),                          // 4: steam.Confirmation
	(*BeginAuthSessionViaCredentialsReceive)(nil), // 5: steam.BeginAuthSessionViaCredentialsReceive
	(*PollAuthSessionStatusSend)(nil),             // 6: steam.PollAuthSessionStatusSend
	(*PollAuthSessionStatusReceive)(nil),          // 7: steam.PollAuthSessionStatusReceive
	(*EmailCode)(nil),                             // 8: steam.EmailCode
}
var file_login_proto_depIdxs = []int32{
	2, // 0: steam.BeginAuthSessionViaCredentialsSend.device_details:type_name -> steam.DeviceDetails
	4, // 1: steam.BeginAuthSessionViaCredentialsReceive.allowed_confirmations:type_name -> steam.Confirmation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
