// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.2
// source: point.proto

package Protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReactionsSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    int32                  `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Targetid      uint64                 `protobuf:"varint,2,opt,name=targetid,proto3" json:"targetid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionsSend) Reset() {
	*x = ReactionsSend{}
	mi := &file_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionsSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionsSend) ProtoMessage() {}

func (x *ReactionsSend) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionsSend.ProtoReflect.Descriptor instead.
func (*ReactionsSend) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{0}
}

func (x *ReactionsSend) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *ReactionsSend) GetTargetid() uint64 {
	if x != nil {
		return x.Targetid
	}
	return 0
}

type ReactionsReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reactionids   []uint32               `protobuf:"varint,1,rep,packed,name=reactionids,proto3" json:"reactionids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionsReceive) Reset() {
	*x = ReactionsReceive{}
	mi := &file_point_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionsReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionsReceive) ProtoMessage() {}

func (x *ReactionsReceive) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionsReceive.ProtoReflect.Descriptor instead.
func (*ReactionsReceive) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{1}
}

func (x *ReactionsReceive) GetReactionids() []uint32 {
	if x != nil {
		return x.Reactionids
	}
	return nil
}

type SummarySend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steamid       uint64                 `protobuf:"fixed64,1,opt,name=steamid,proto3" json:"steamid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarySend) Reset() {
	*x = SummarySend{}
	mi := &file_point_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarySend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarySend) ProtoMessage() {}

func (x *SummarySend) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarySend.ProtoReflect.Descriptor instead.
func (*SummarySend) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{2}
}

func (x *SummarySend) GetSteamid() uint64 {
	if x != nil {
		return x.Steamid
	}
	return 0
}

type SummaryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        uint64                 `protobuf:"varint,1,opt,name=points,proto3" json:"points,omitempty"`
	PointsEarned  int64                  `protobuf:"varint,2,opt,name=points_earned,json=pointsEarned,proto3" json:"points_earned,omitempty"`
	PointsSpent   int64                  `protobuf:"varint,3,opt,name=points_spent,json=pointsSpent,proto3" json:"points_spent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryPoint) Reset() {
	*x = SummaryPoint{}
	mi := &file_point_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryPoint) ProtoMessage() {}

func (x *SummaryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryPoint.ProtoReflect.Descriptor instead.
func (*SummaryPoint) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{3}
}

func (x *SummaryPoint) GetPoints() uint64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *SummaryPoint) GetPointsEarned() int64 {
	if x != nil {
		return x.PointsEarned
	}
	return 0
}

func (x *SummaryPoint) GetPointsSpent() int64 {
	if x != nil {
		return x.PointsSpent
	}
	return 0
}

type SummaryReceive struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Summary          *SummaryPoint          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	TimestampUpdated uint32                 `protobuf:"varint,2,opt,name=timestamp_updated,json=timestampUpdated,proto3" json:"timestamp_updated,omitempty"`
	AuditidHighwater uint64                 `protobuf:"varint,3,opt,name=auditid_highwater,json=auditidHighwater,proto3" json:"auditid_highwater,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SummaryReceive) Reset() {
	*x = SummaryReceive{}
	mi := &file_point_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryReceive) ProtoMessage() {}

func (x *SummaryReceive) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryReceive.ProtoReflect.Descriptor instead.
func (*SummaryReceive) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{4}
}

func (x *SummaryReceive) GetSummary() *SummaryPoint {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *SummaryReceive) GetTimestampUpdated() uint32 {
	if x != nil {
		return x.TimestampUpdated
	}
	return 0
}

func (x *SummaryReceive) GetAuditidHighwater() uint64 {
	if x != nil {
		return x.AuditidHighwater
	}
	return 0
}

type AddReactionSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    int32                  `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Targetid      uint64                 `protobuf:"varint,2,opt,name=targetid,proto3" json:"targetid,omitempty"`
	Reactionid    uint32                 `protobuf:"varint,3,opt,name=reactionid,proto3" json:"reactionid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReactionSend) Reset() {
	*x = AddReactionSend{}
	mi := &file_point_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReactionSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReactionSend) ProtoMessage() {}

func (x *AddReactionSend) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReactionSend.ProtoReflect.Descriptor instead.
func (*AddReactionSend) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{5}
}

func (x *AddReactionSend) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *AddReactionSend) GetTargetid() uint64 {
	if x != nil {
		return x.Targetid
	}
	return 0
}

func (x *AddReactionSend) GetReactionid() uint32 {
	if x != nil {
		return x.Reactionid
	}
	return 0
}

type AddReactionReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReactionReceive) Reset() {
	*x = AddReactionReceive{}
	mi := &file_point_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReactionReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReactionReceive) ProtoMessage() {}

func (x *AddReactionReceive) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReactionReceive.ProtoReflect.Descriptor instead.
func (*AddReactionReceive) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{6}
}

var File_point_proto protoreflect.FileDescriptor

const file_point_proto_rawDesc = "" +
	"\n" +
	"\vpoint.proto\x12\x05steam\"L\n" +
	"\rReactionsSend\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\x05R\n" +
	"targetType\x12\x1a\n" +
	"\btargetid\x18\x02 \x01(\x04R\btargetid\"4\n" +
	"\x10ReactionsReceive\x12 \n" +
	"\vreactionids\x18\x01 \x03(\rR\vreactionids\"'\n" +
	"\vSummarySend\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\"n\n" +
	"\fSummaryPoint\x12\x16\n" +
	"\x06points\x18\x01 \x01(\x04R\x06points\x12#\n" +
	"\rpoints_earned\x18\x02 \x01(\x03R\fpointsEarned\x12!\n" +
	"\fpoints_spent\x18\x03 \x01(\x03R\vpointsSpent\"\x99\x01\n" +
	"\x0eSummaryReceive\x12-\n" +
	"\asummary\x18\x01 \x01(\v2\x13.steam.SummaryPointR\asummary\x12+\n" +
	"\x11timestamp_updated\x18\x02 \x01(\rR\x10timestampUpdated\x12+\n" +
	"\x11auditid_highwater\x18\x03 \x01(\x04R\x10auditidHighwater\"n\n" +
	"\x0fAddReactionSend\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\x05R\n" +
	"targetType\x12\x1a\n" +
	"\btargetid\x18\x02 \x01(\x04R\btargetid\x12\x1e\n" +
	"\n" +
	"reactionid\x18\x03 \x01(\rR\n" +
	"reactionid\"\x14\n" +
	"\x12AddReactionReceiveB\vZ\t../Protocb\x06proto3"

var (
	file_point_proto_rawDescOnce sync.Once
	file_point_proto_rawDescData []byte
)

func file_point_proto_rawDescGZIP() []byte {
	file_point_proto_rawDescOnce.Do(func() {
		file_point_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_point_proto_rawDesc), len(file_point_proto_rawDesc)))
	})
	return file_point_proto_rawDescData
}

var file_point_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_point_proto_goTypes = []any{
	(*ReactionsSend)(nil),      // 0: steam.ReactionsSend
	(*ReactionsReceive)(nil),   // 1: steam.ReactionsReceive
	(*SummarySend)(nil),        // 2: steam.SummarySend
	(*SummaryPoint)(nil),       // 3: steam.SummaryPoint
	(*SummaryReceive)(nil),     // 4: steam.SummaryReceive
	(*AddReactionSend)(nil),    // 5: steam.AddReactionSend
	(*AddReactionReceive)(nil), // 6: steam.AddReactionReceive
}
var file_point_proto_depIdxs = []int32{
	3, // 0: steam.SummaryReceive.summary:type_name -> steam.SummaryPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_point_proto_init() }
func file_point_proto_init() {
	if File_point_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_point_proto_rawDesc), len(file_point_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_point_proto_goTypes,
		DependencyIndexes: file_point_proto_depIdxs,
		MessageInfos:      file_point_proto_msgTypes,
	}.Build()
	File_point_proto = out.File
	file_point_proto_goTypes = nil
	file_point_proto_depIdxs = nil
}
