// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.2
// source: store.proto

package Protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreItems    []*StoreItem           `protobuf:"bytes,1,rep,name=store_items,json=storeItems,proto3" json:"store_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetStoreItems() []*StoreItem {
	if x != nil {
		return x.StoreItems
	}
	return nil
}

type StoreItem struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	ItemType                        uint32                 `protobuf:"varint,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Id                              uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Success                         uint32                 `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Visible                         bool                   `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"`
	UnvailableForCountryRestriction bool                   `protobuf:"varint,5,opt,name=unvailable_for_country_restriction,json=unvailableForCountryRestriction,proto3" json:"unvailable_for_country_restriction,omitempty"`
	Name                            string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	StoreUrlPath                    string                 `protobuf:"bytes,7,opt,name=store_url_path,json=storeUrlPath,proto3" json:"store_url_path,omitempty"`
	Appid                           uint32                 `protobuf:"varint,9,opt,name=appid,proto3" json:"appid,omitempty"`
	Type                            uint32                 `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	IncludedTypes                   []uint32               `protobuf:"varint,11,rep,packed,name=included_types,json=includedTypes,proto3" json:"included_types,omitempty"`
	IncludedAppids                  []uint32               `protobuf:"varint,12,rep,packed,name=included_appids,json=includedAppids,proto3" json:"included_appids,omitempty"`
	IsFree                          bool                   `protobuf:"varint,13,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	IsEarlyAccess                   bool                   `protobuf:"varint,14,opt,name=is_early_access,json=isEarlyAccess,proto3" json:"is_early_access,omitempty"`
	RelatedItems                    *RelatedItem           `protobuf:"bytes,15,opt,name=related_items,json=relatedItems,proto3" json:"related_items,omitempty"`
	IncludedItems                   *IncludedItem          `protobuf:"bytes,16,opt,name=included_items,json=includedItems,proto3" json:"included_items,omitempty"`
	ContentDescriptorids            []uint32               `protobuf:"varint,20,rep,packed,name=content_descriptorids,json=contentDescriptorids,proto3" json:"content_descriptorids,omitempty"`
	Tagids                          []uint32               `protobuf:"varint,21,rep,packed,name=tagids,proto3" json:"tagids,omitempty"`
	Categories                      *Category              `protobuf:"bytes,22,opt,name=categories,proto3" json:"categories,omitempty"`
	Reviews                         *Review                `protobuf:"bytes,23,opt,name=reviews,proto3" json:"reviews,omitempty"`
	BasicInfo                       *BasicInfo             `protobuf:"bytes,24,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"`
	Tags                            []*Tag                 `protobuf:"bytes,25,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets                          *Assets                `protobuf:"bytes,30,opt,name=assets,proto3" json:"assets,omitempty"`
	Release                         *Release               `protobuf:"bytes,31,opt,name=release,proto3" json:"release,omitempty"`
	Platforms                       uint32                 `protobuf:"varint,32,opt,name=platforms,proto3" json:"platforms,omitempty"`
	GameRating                      uint32                 `protobuf:"varint,33,opt,name=game_rating,json=gameRating,proto3" json:"game_rating,omitempty"` //?
	BestPurchaseOption              *Option                `protobuf:"bytes,40,opt,name=best_purchase_option,json=bestPurchaseOption,proto3" json:"best_purchase_option,omitempty"`
	PurchaseOptions                 []*Option              `protobuf:"bytes,41,rep,name=purchase_options,json=purchaseOptions,proto3" json:"purchase_options,omitempty"`
	Accessories                     []*Option              `protobuf:"bytes,42,rep,name=accessories,proto3" json:"accessories,omitempty"`
	SelfPurchaseOption              *Option                `protobuf:"bytes,43,opt,name=self_purchase_option,json=selfPurchaseOption,proto3" json:"self_purchase_option,omitempty"`
	Screenshots                     *ScreenShots           `protobuf:"bytes,50,opt,name=screenshots,proto3" json:"screenshots,omitempty"`
	Trailers                        []*Trailer             `protobuf:"bytes,51,rep,name=trailers,proto3" json:"trailers,omitempty"`
	SupportedLanguages              []*SupportLanguage     `protobuf:"bytes,52,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	StoreUrlPathOverride            string                 `protobuf:"bytes,53,opt,name=store_url_path_override,json=storeUrlPathOverride,proto3" json:"store_url_path_override,omitempty"`
	FreeWeekend                     *FreeWeekend           `protobuf:"bytes,54,opt,name=free_weekend,json=freeWeekend,proto3" json:"free_weekend,omitempty"`
	Unlisted                        bool                   `protobuf:"varint,55,opt,name=unlisted,proto3" json:"unlisted,omitempty"`
	GameCount                       uint32                 `protobuf:"varint,56,opt,name=game_count,json=gameCount,proto3" json:"game_count,omitempty"`
	InternalName                    string                 `protobuf:"bytes,57,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	FullDescription                 string                 `protobuf:"bytes,58,opt,name=full_description,json=fullDescription,proto3" json:"full_description,omitempty"`
	IsFreeTemporarily               bool                   `protobuf:"varint,59,opt,name=is_free_temporarily,json=isFreeTemporarily,proto3" json:"is_free_temporarily,omitempty"`
	AssetsWithoutOverrides          *Assets                `protobuf:"bytes,60,opt,name=assets_without_overrides,json=assetsWithoutOverrides,proto3" json:"assets_without_overrides,omitempty"`
	UserFilterFailure               *UserFilterFailure     `protobuf:"bytes,70,opt,name=user_filter_failure,json=userFilterFailure,proto3" json:"user_filter_failure,omitempty"`
	Links                           []*Link                `protobuf:"bytes,71,rep,name=links,proto3" json:"links,omitempty"` //? 猜测
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *StoreItem) Reset() {
	*x = StoreItem{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreItem) ProtoMessage() {}

func (x *StoreItem) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreItem.ProtoReflect.Descriptor instead.
func (*StoreItem) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

func (x *StoreItem) GetItemType() uint32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *StoreItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreItem) GetSuccess() uint32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *StoreItem) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *StoreItem) GetUnvailableForCountryRestriction() bool {
	if x != nil {
		return x.UnvailableForCountryRestriction
	}
	return false
}

func (x *StoreItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreItem) GetStoreUrlPath() string {
	if x != nil {
		return x.StoreUrlPath
	}
	return ""
}

func (x *StoreItem) GetAppid() uint32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *StoreItem) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *StoreItem) GetIncludedTypes() []uint32 {
	if x != nil {
		return x.IncludedTypes
	}
	return nil
}

func (x *StoreItem) GetIncludedAppids() []uint32 {
	if x != nil {
		return x.IncludedAppids
	}
	return nil
}

func (x *StoreItem) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *StoreItem) GetIsEarlyAccess() bool {
	if x != nil {
		return x.IsEarlyAccess
	}
	return false
}

func (x *StoreItem) GetRelatedItems() *RelatedItem {
	if x != nil {
		return x.RelatedItems
	}
	return nil
}

func (x *StoreItem) GetIncludedItems() *IncludedItem {
	if x != nil {
		return x.IncludedItems
	}
	return nil
}

func (x *StoreItem) GetContentDescriptorids() []uint32 {
	if x != nil {
		return x.ContentDescriptorids
	}
	return nil
}

func (x *StoreItem) GetTagids() []uint32 {
	if x != nil {
		return x.Tagids
	}
	return nil
}

func (x *StoreItem) GetCategories() *Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *StoreItem) GetReviews() *Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *StoreItem) GetBasicInfo() *BasicInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *StoreItem) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StoreItem) GetAssets() *Assets {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *StoreItem) GetRelease() *Release {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *StoreItem) GetPlatforms() uint32 {
	if x != nil {
		return x.Platforms
	}
	return 0
}

func (x *StoreItem) GetGameRating() uint32 {
	if x != nil {
		return x.GameRating
	}
	return 0
}

func (x *StoreItem) GetBestPurchaseOption() *Option {
	if x != nil {
		return x.BestPurchaseOption
	}
	return nil
}

func (x *StoreItem) GetPurchaseOptions() []*Option {
	if x != nil {
		return x.PurchaseOptions
	}
	return nil
}

func (x *StoreItem) GetAccessories() []*Option {
	if x != nil {
		return x.Accessories
	}
	return nil
}

func (x *StoreItem) GetSelfPurchaseOption() *Option {
	if x != nil {
		return x.SelfPurchaseOption
	}
	return nil
}

func (x *StoreItem) GetScreenshots() *ScreenShots {
	if x != nil {
		return x.Screenshots
	}
	return nil
}

func (x *StoreItem) GetTrailers() []*Trailer {
	if x != nil {
		return x.Trailers
	}
	return nil
}

func (x *StoreItem) GetSupportedLanguages() []*SupportLanguage {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

func (x *StoreItem) GetStoreUrlPathOverride() string {
	if x != nil {
		return x.StoreUrlPathOverride
	}
	return ""
}

func (x *StoreItem) GetFreeWeekend() *FreeWeekend {
	if x != nil {
		return x.FreeWeekend
	}
	return nil
}

func (x *StoreItem) GetUnlisted() bool {
	if x != nil {
		return x.Unlisted
	}
	return false
}

func (x *StoreItem) GetGameCount() uint32 {
	if x != nil {
		return x.GameCount
	}
	return 0
}

func (x *StoreItem) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *StoreItem) GetFullDescription() string {
	if x != nil {
		return x.FullDescription
	}
	return ""
}

func (x *StoreItem) GetIsFreeTemporarily() bool {
	if x != nil {
		return x.IsFreeTemporarily
	}
	return false
}

func (x *StoreItem) GetAssetsWithoutOverrides() *Assets {
	if x != nil {
		return x.AssetsWithoutOverrides
	}
	return nil
}

func (x *StoreItem) GetUserFilterFailure() *UserFilterFailure {
	if x != nil {
		return x.UserFilterFailure
	}
	return nil
}

func (x *StoreItem) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type Assets struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AssetUrlFormat    string                 `protobuf:"bytes,1,opt,name=asset_url_format,json=assetUrlFormat,proto3" json:"asset_url_format,omitempty"`
	MainCapsule       string                 `protobuf:"bytes,2,opt,name=main_capsule,json=mainCapsule,proto3" json:"main_capsule,omitempty"`
	SmallCapsule      string                 `protobuf:"bytes,3,opt,name=small_capsule,json=smallCapsule,proto3" json:"small_capsule,omitempty"`
	Header            string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	PackageHeader     string                 `protobuf:"bytes,5,opt,name=package_header,json=packageHeader,proto3" json:"package_header,omitempty"`
	PageBackground    string                 `protobuf:"bytes,6,opt,name=page_background,json=pageBackground,proto3" json:"page_background,omitempty"`
	HeroCapsule       string                 `protobuf:"bytes,7,opt,name=hero_capsule,json=heroCapsule,proto3" json:"hero_capsule,omitempty"`
	HeroCapsule_2X    string                 `protobuf:"bytes,8,opt,name=hero_capsule_2x,json=heroCapsule2x,proto3" json:"hero_capsule_2x,omitempty"`
	LibraryCapsule    string                 `protobuf:"bytes,9,opt,name=library_capsule,json=libraryCapsule,proto3" json:"library_capsule,omitempty"`
	LibraryCapsule_2X string                 `protobuf:"bytes,10,opt,name=library_capsule_2x,json=libraryCapsule2x,proto3" json:"library_capsule_2x,omitempty"`
	LibraryHero       string                 `protobuf:"bytes,11,opt,name=library_hero,json=libraryHero,proto3" json:"library_hero,omitempty"`
	LibraryHero_2X    string                 `protobuf:"bytes,12,opt,name=library_hero_2x,json=libraryHero2x,proto3" json:"library_hero_2x,omitempty"`
	CommunityIcon     string                 `protobuf:"bytes,13,opt,name=community_icon,json=communityIcon,proto3" json:"community_icon,omitempty"`
	ClanAvatar        string                 `protobuf:"bytes,14,opt,name=clan_avatar,json=clanAvatar,proto3" json:"clan_avatar,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Assets) Reset() {
	*x = Assets{}
	mi := &file_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets) ProtoMessage() {}

func (x *Assets) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets.ProtoReflect.Descriptor instead.
func (*Assets) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{2}
}

func (x *Assets) GetAssetUrlFormat() string {
	if x != nil {
		return x.AssetUrlFormat
	}
	return ""
}

func (x *Assets) GetMainCapsule() string {
	if x != nil {
		return x.MainCapsule
	}
	return ""
}

func (x *Assets) GetSmallCapsule() string {
	if x != nil {
		return x.SmallCapsule
	}
	return ""
}

func (x *Assets) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Assets) GetPackageHeader() string {
	if x != nil {
		return x.PackageHeader
	}
	return ""
}

func (x *Assets) GetPageBackground() string {
	if x != nil {
		return x.PageBackground
	}
	return ""
}

func (x *Assets) GetHeroCapsule() string {
	if x != nil {
		return x.HeroCapsule
	}
	return ""
}

func (x *Assets) GetHeroCapsule_2X() string {
	if x != nil {
		return x.HeroCapsule_2X
	}
	return ""
}

func (x *Assets) GetLibraryCapsule() string {
	if x != nil {
		return x.LibraryCapsule
	}
	return ""
}

func (x *Assets) GetLibraryCapsule_2X() string {
	if x != nil {
		return x.LibraryCapsule_2X
	}
	return ""
}

func (x *Assets) GetLibraryHero() string {
	if x != nil {
		return x.LibraryHero
	}
	return ""
}

func (x *Assets) GetLibraryHero_2X() string {
	if x != nil {
		return x.LibraryHero_2X
	}
	return ""
}

func (x *Assets) GetCommunityIcon() string {
	if x != nil {
		return x.CommunityIcon
	}
	return ""
}

func (x *Assets) GetClanAvatar() string {
	if x != nil {
		return x.ClanAvatar
	}
	return ""
}

type Option struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Packageid                    int32                  `protobuf:"varint,1,opt,name=packageid,proto3" json:"packageid,omitempty"`
	Bundleid                     int32                  `protobuf:"varint,2,opt,name=bundleid,proto3" json:"bundleid,omitempty"`
	PurchaseOptionName           string                 `protobuf:"bytes,3,opt,name=purchase_option_name,json=purchaseOptionName,proto3" json:"purchase_option_name,omitempty"`
	FinalPriceInCents            int64                  `protobuf:"varint,5,opt,name=final_price_in_cents,json=finalPriceInCents,proto3" json:"final_price_in_cents,omitempty"`
	OriginalPriceInCents         int64                  `protobuf:"varint,6,opt,name=original_price_in_cents,json=originalPriceInCents,proto3" json:"original_price_in_cents,omitempty"`
	UserFinalPriceInCents        int64                  `protobuf:"varint,7,opt,name=user_final_price_in_cents,json=userFinalPriceInCents,proto3" json:"user_final_price_in_cents,omitempty"`
	FormattedFinalPrice          string                 `protobuf:"bytes,8,opt,name=formatted_final_price,json=formattedFinalPrice,proto3" json:"formatted_final_price,omitempty"`
	FormattedOriginalPrice       string                 `protobuf:"bytes,9,opt,name=formatted_original_price,json=formattedOriginalPrice,proto3" json:"formatted_original_price,omitempty"`
	DiscountPct                  int32                  `protobuf:"varint,10,opt,name=discount_pct,json=discountPct,proto3" json:"discount_pct,omitempty"`
	UserDiscountPct              int32                  `protobuf:"varint,11,opt,name=user_discount_pct,json=userDiscountPct,proto3" json:"user_discount_pct,omitempty"`
	BundleDiscountPct            int32                  `protobuf:"varint,12,opt,name=bundle_discount_pct,json=bundleDiscountPct,proto3" json:"bundle_discount_pct,omitempty"`
	ActiveDiscounts              []bool                 `protobuf:"varint,20,rep,packed,name=active_discounts,json=activeDiscounts,proto3" json:"active_discounts,omitempty"`               //?
	UserActiveDiscounts          []bool                 `protobuf:"varint,21,rep,packed,name=user_active_discounts,json=userActiveDiscounts,proto3" json:"user_active_discounts,omitempty"` //?
	InactiveDiscounts            []bool                 `protobuf:"varint,22,rep,packed,name=inactive_discounts,json=inactiveDiscounts,proto3" json:"inactive_discounts,omitempty"`         //?
	UserCanPurchase              bool                   `protobuf:"varint,30,opt,name=user_can_purchase,json=userCanPurchase,proto3" json:"user_can_purchase,omitempty"`
	UserCanPurchaseAsGift        bool                   `protobuf:"varint,31,opt,name=user_can_purchase_as_gift,json=userCanPurchaseAsGift,proto3" json:"user_can_purchase_as_gift,omitempty"`
	IsCommercialLicense          bool                   `protobuf:"varint,40,opt,name=is_commercial_license,json=isCommercialLicense,proto3" json:"is_commercial_license,omitempty"`
	ShouldSuppressDiscountPct    bool                   `protobuf:"varint,41,opt,name=should_suppress_discount_pct,json=shouldSuppressDiscountPct,proto3" json:"should_suppress_discount_pct,omitempty"`
	HideDiscountPctForCompliance bool                   `protobuf:"varint,42,opt,name=hide_discount_pct_for_compliance,json=hideDiscountPctForCompliance,proto3" json:"hide_discount_pct_for_compliance,omitempty"`
	IncludedGameCount            int32                  `protobuf:"varint,43,opt,name=included_game_count,json=includedGameCount,proto3" json:"included_game_count,omitempty"`
	LowestRecentPriceInCents     int64                  `protobuf:"varint,44,opt,name=lowest_recent_price_in_cents,json=lowestRecentPriceInCents,proto3" json:"lowest_recent_price_in_cents,omitempty"`
	RequiresShipping             bool                   `protobuf:"varint,45,opt,name=requires_shipping,json=requiresShipping,proto3" json:"requires_shipping,omitempty"`
	RecurrenceInfo               bool                   `protobuf:"varint,46,opt,name=recurrence_info,json=recurrenceInfo,proto3" json:"recurrence_info,omitempty"` //?
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{3}
}

func (x *Option) GetPackageid() int32 {
	if x != nil {
		return x.Packageid
	}
	return 0
}

func (x *Option) GetBundleid() int32 {
	if x != nil {
		return x.Bundleid
	}
	return 0
}

func (x *Option) GetPurchaseOptionName() string {
	if x != nil {
		return x.PurchaseOptionName
	}
	return ""
}

func (x *Option) GetFinalPriceInCents() int64 {
	if x != nil {
		return x.FinalPriceInCents
	}
	return 0
}

func (x *Option) GetOriginalPriceInCents() int64 {
	if x != nil {
		return x.OriginalPriceInCents
	}
	return 0
}

func (x *Option) GetUserFinalPriceInCents() int64 {
	if x != nil {
		return x.UserFinalPriceInCents
	}
	return 0
}

func (x *Option) GetFormattedFinalPrice() string {
	if x != nil {
		return x.FormattedFinalPrice
	}
	return ""
}

func (x *Option) GetFormattedOriginalPrice() string {
	if x != nil {
		return x.FormattedOriginalPrice
	}
	return ""
}

func (x *Option) GetDiscountPct() int32 {
	if x != nil {
		return x.DiscountPct
	}
	return 0
}

func (x *Option) GetUserDiscountPct() int32 {
	if x != nil {
		return x.UserDiscountPct
	}
	return 0
}

func (x *Option) GetBundleDiscountPct() int32 {
	if x != nil {
		return x.BundleDiscountPct
	}
	return 0
}

func (x *Option) GetActiveDiscounts() []bool {
	if x != nil {
		return x.ActiveDiscounts
	}
	return nil
}

func (x *Option) GetUserActiveDiscounts() []bool {
	if x != nil {
		return x.UserActiveDiscounts
	}
	return nil
}

func (x *Option) GetInactiveDiscounts() []bool {
	if x != nil {
		return x.InactiveDiscounts
	}
	return nil
}

func (x *Option) GetUserCanPurchase() bool {
	if x != nil {
		return x.UserCanPurchase
	}
	return false
}

func (x *Option) GetUserCanPurchaseAsGift() bool {
	if x != nil {
		return x.UserCanPurchaseAsGift
	}
	return false
}

func (x *Option) GetIsCommercialLicense() bool {
	if x != nil {
		return x.IsCommercialLicense
	}
	return false
}

func (x *Option) GetShouldSuppressDiscountPct() bool {
	if x != nil {
		return x.ShouldSuppressDiscountPct
	}
	return false
}

func (x *Option) GetHideDiscountPctForCompliance() bool {
	if x != nil {
		return x.HideDiscountPctForCompliance
	}
	return false
}

func (x *Option) GetIncludedGameCount() int32 {
	if x != nil {
		return x.IncludedGameCount
	}
	return 0
}

func (x *Option) GetLowestRecentPriceInCents() int64 {
	if x != nil {
		return x.LowestRecentPriceInCents
	}
	return 0
}

func (x *Option) GetRequiresShipping() bool {
	if x != nil {
		return x.RequiresShipping
	}
	return false
}

func (x *Option) GetRecurrenceInfo() bool {
	if x != nil {
		return x.RecurrenceInfo
	}
	return false
}

type Category struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SupportedPlayerCategoryids uint32                 `protobuf:"varint,2,opt,name=supported_player_categoryids,json=supportedPlayerCategoryids,proto3" json:"supported_player_categoryids,omitempty"`
	FeatureCategoryids         uint32                 `protobuf:"varint,3,opt,name=feature_categoryids,json=featureCategoryids,proto3" json:"feature_categoryids,omitempty"`
	ControllerCategoryids      uint32                 `protobuf:"varint,4,opt,name=controller_categoryids,json=controllerCategoryids,proto3" json:"controller_categoryids,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{4}
}

func (x *Category) GetSupportedPlayerCategoryids() uint32 {
	if x != nil {
		return x.SupportedPlayerCategoryids
	}
	return 0
}

func (x *Category) GetFeatureCategoryids() uint32 {
	if x != nil {
		return x.FeatureCategoryids
	}
	return 0
}

func (x *Category) GetControllerCategoryids() uint32 {
	if x != nil {
		return x.ControllerCategoryids
	}
	return 0
}

type ScreenShots struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AllAgesScreenshots       []*ScreenShotsAge      `protobuf:"bytes,2,rep,name=all_ages_screenshots,json=allAgesScreenshots,proto3" json:"all_ages_screenshots,omitempty"`
	MatureContentScreenshots []*ScreenShotsAge      `protobuf:"bytes,3,rep,name=mature_content_screenshots,json=matureContentScreenshots,proto3" json:"mature_content_screenshots,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ScreenShots) Reset() {
	*x = ScreenShots{}
	mi := &file_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenShots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenShots) ProtoMessage() {}

func (x *ScreenShots) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenShots.ProtoReflect.Descriptor instead.
func (*ScreenShots) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{5}
}

func (x *ScreenShots) GetAllAgesScreenshots() []*ScreenShotsAge {
	if x != nil {
		return x.AllAgesScreenshots
	}
	return nil
}

func (x *ScreenShots) GetMatureContentScreenshots() []*ScreenShotsAge {
	if x != nil {
		return x.MatureContentScreenshots
	}
	return nil
}

type ScreenShotsAge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Ordinal       int32                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenShotsAge) Reset() {
	*x = ScreenShotsAge{}
	mi := &file_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenShotsAge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenShotsAge) ProtoMessage() {}

func (x *ScreenShotsAge) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenShotsAge.ProtoReflect.Descriptor instead.
func (*ScreenShotsAge) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{6}
}

func (x *ScreenShotsAge) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ScreenShotsAge) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

type RelatedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentAppid   uint32                 `protobuf:"varint,1,opt,name=parent_appid,json=parentAppid,proto3" json:"parent_appid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedItem) Reset() {
	*x = RelatedItem{}
	mi := &file_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedItem) ProtoMessage() {}

func (x *RelatedItem) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedItem.ProtoReflect.Descriptor instead.
func (*RelatedItem) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{7}
}

func (x *RelatedItem) GetParentAppid() uint32 {
	if x != nil {
		return x.ParentAppid
	}
	return 0
}

type IncludedItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncludedApps     []*StoreItem           `protobuf:"bytes,1,rep,name=included_apps,json=includedApps,proto3" json:"included_apps,omitempty"`
	IncludedPackages []*StoreItem           `protobuf:"bytes,2,rep,name=included_packages,json=includedPackages,proto3" json:"included_packages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IncludedItem) Reset() {
	*x = IncludedItem{}
	mi := &file_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncludedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncludedItem) ProtoMessage() {}

func (x *IncludedItem) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncludedItem.ProtoReflect.Descriptor instead.
func (*IncludedItem) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{8}
}

func (x *IncludedItem) GetIncludedApps() []*StoreItem {
	if x != nil {
		return x.IncludedApps
	}
	return nil
}

func (x *IncludedItem) GetIncludedPackages() []*StoreItem {
	if x != nil {
		return x.IncludedPackages
	}
	return nil
}

type BasicInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ShortDescription string                 `protobuf:"bytes,1,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Publishers       []*Publisher           `protobuf:"bytes,2,rep,name=publishers,proto3" json:"publishers,omitempty"`
	Developers       []*Publisher           `protobuf:"bytes,3,rep,name=developers,proto3" json:"developers,omitempty"`
	Franchises       []*Publisher           `protobuf:"bytes,4,rep,name=franchises,proto3" json:"franchises,omitempty"`
	CapsuleHeadline  string                 `protobuf:"bytes,5,opt,name=capsule_headline,json=capsuleHeadline,proto3" json:"capsule_headline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BasicInfo) Reset() {
	*x = BasicInfo{}
	mi := &file_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfo) ProtoMessage() {}

func (x *BasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfo.ProtoReflect.Descriptor instead.
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{9}
}

func (x *BasicInfo) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *BasicInfo) GetPublishers() []*Publisher {
	if x != nil {
		return x.Publishers
	}
	return nil
}

func (x *BasicInfo) GetDevelopers() []*Publisher {
	if x != nil {
		return x.Developers
	}
	return nil
}

func (x *BasicInfo) GetFranchises() []*Publisher {
	if x != nil {
		return x.Franchises
	}
	return nil
}

func (x *BasicInfo) GetCapsuleHeadline() string {
	if x != nil {
		return x.CapsuleHeadline
	}
	return ""
}

type Publisher struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatorClanAccountId uint32                 `protobuf:"varint,2,opt,name=creator_clan_account_id,json=creatorClanAccountId,proto3" json:"creator_clan_account_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Publisher) Reset() {
	*x = Publisher{}
	mi := &file_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publisher) ProtoMessage() {}

func (x *Publisher) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publisher.ProtoReflect.Descriptor instead.
func (*Publisher) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{10}
}

func (x *Publisher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Publisher) GetCreatorClanAccountId() uint32 {
	if x != nil {
		return x.CreatorClanAccountId
	}
	return 0
}

type Review struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SummaryFiltered   *Summary               `protobuf:"bytes,1,opt,name=summary_filtered,json=summaryFiltered,proto3" json:"summary_filtered,omitempty"`
	SummaryUnfiltered *Summary               `protobuf:"bytes,2,opt,name=summary_unfiltered,json=summaryUnfiltered,proto3" json:"summary_unfiltered,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{11}
}

func (x *Review) GetSummaryFiltered() *Summary {
	if x != nil {
		return x.SummaryFiltered
	}
	return nil
}

func (x *Review) GetSummaryUnfiltered() *Summary {
	if x != nil {
		return x.SummaryUnfiltered
	}
	return nil
}

type Summary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReviewCount      uint32                 `protobuf:"varint,1,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	PercentPositive  int32                  `protobuf:"varint,2,opt,name=percent_positive,json=percentPositive,proto3" json:"percent_positive,omitempty"`
	ReviewScore      int32                  `protobuf:"varint,3,opt,name=review_score,json=reviewScore,proto3" json:"review_score,omitempty"`
	ReviewScoreLabel string                 `protobuf:"bytes,4,opt,name=review_score_label,json=reviewScoreLabel,proto3" json:"review_score_label,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{12}
}

func (x *Summary) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *Summary) GetPercentPositive() int32 {
	if x != nil {
		return x.PercentPositive
	}
	return 0
}

func (x *Summary) GetReviewScore() int32 {
	if x != nil {
		return x.ReviewScore
	}
	return 0
}

func (x *Summary) GetReviewScoreLabel() string {
	if x != nil {
		return x.ReviewScoreLabel
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tagid         uint32                 `protobuf:"varint,1,opt,name=tagid,proto3" json:"tagid,omitempty"`
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{13}
}

func (x *Tag) GetTagid() uint32 {
	if x != nil {
		return x.Tagid
	}
	return 0
}

func (x *Tag) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Release struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SteamReleaseDate         uint32                 `protobuf:"varint,1,opt,name=steam_release_date,json=steamReleaseDate,proto3" json:"steam_release_date,omitempty"`
	OriginalReleaseDate      uint32                 `protobuf:"varint,2,opt,name=original_release_date,json=originalReleaseDate,proto3" json:"original_release_date,omitempty"`
	OriginalSteamReleaseDate uint32                 `protobuf:"varint,3,opt,name=original_steam_release_date,json=originalSteamReleaseDate,proto3" json:"original_steam_release_date,omitempty"`
	IsComingSoon             bool                   `protobuf:"varint,4,opt,name=is_coming_soon,json=isComingSoon,proto3" json:"is_coming_soon,omitempty"`
	IsPreload                bool                   `protobuf:"varint,5,opt,name=is_preload,json=isPreload,proto3" json:"is_preload,omitempty"`
	CustomReleaseDateMessage string                 `protobuf:"bytes,6,opt,name=custom_release_date_message,json=customReleaseDateMessage,proto3" json:"custom_release_date_message,omitempty"`
	IsAbridgedReleaseDate    bool                   `protobuf:"varint,7,opt,name=is_abridged_release_date,json=isAbridgedReleaseDate,proto3" json:"is_abridged_release_date,omitempty"`
	ComingSoonDisplay        string                 `protobuf:"bytes,8,opt,name=coming_soon_display,json=comingSoonDisplay,proto3" json:"coming_soon_display,omitempty"`
	IsEarlyAccess            bool                   `protobuf:"varint,10,opt,name=is_early_access,json=isEarlyAccess,proto3" json:"is_early_access,omitempty"`
	MacReleaseDate           uint32                 `protobuf:"varint,20,opt,name=mac_release_date,json=macReleaseDate,proto3" json:"mac_release_date,omitempty"`
	LinuxReleaseDate         uint32                 `protobuf:"varint,21,opt,name=linux_release_date,json=linuxReleaseDate,proto3" json:"linux_release_date,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{14}
}

func (x *Release) GetSteamReleaseDate() uint32 {
	if x != nil {
		return x.SteamReleaseDate
	}
	return 0
}

func (x *Release) GetOriginalReleaseDate() uint32 {
	if x != nil {
		return x.OriginalReleaseDate
	}
	return 0
}

func (x *Release) GetOriginalSteamReleaseDate() uint32 {
	if x != nil {
		return x.OriginalSteamReleaseDate
	}
	return 0
}

func (x *Release) GetIsComingSoon() bool {
	if x != nil {
		return x.IsComingSoon
	}
	return false
}

func (x *Release) GetIsPreload() bool {
	if x != nil {
		return x.IsPreload
	}
	return false
}

func (x *Release) GetCustomReleaseDateMessage() string {
	if x != nil {
		return x.CustomReleaseDateMessage
	}
	return ""
}

func (x *Release) GetIsAbridgedReleaseDate() bool {
	if x != nil {
		return x.IsAbridgedReleaseDate
	}
	return false
}

func (x *Release) GetComingSoonDisplay() string {
	if x != nil {
		return x.ComingSoonDisplay
	}
	return ""
}

func (x *Release) GetIsEarlyAccess() bool {
	if x != nil {
		return x.IsEarlyAccess
	}
	return false
}

func (x *Release) GetMacReleaseDate() uint32 {
	if x != nil {
		return x.MacReleaseDate
	}
	return 0
}

func (x *Release) GetLinuxReleaseDate() uint32 {
	if x != nil {
		return x.LinuxReleaseDate
	}
	return 0
}

type Trailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Highlights    *TrailerInfo           `protobuf:"bytes,1,opt,name=highlights,proto3" json:"highlights,omitempty"`
	OtherTrailers *TrailerInfo           `protobuf:"bytes,2,opt,name=other_trailers,json=otherTrailers,proto3" json:"other_trailers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trailer) Reset() {
	*x = Trailer{}
	mi := &file_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trailer) ProtoMessage() {}

func (x *Trailer) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trailer.ProtoReflect.Descriptor instead.
func (*Trailer) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{15}
}

func (x *Trailer) GetHighlights() *TrailerInfo {
	if x != nil {
		return x.Highlights
	}
	return nil
}

func (x *Trailer) GetOtherTrailers() *TrailerInfo {
	if x != nil {
		return x.OtherTrailers
	}
	return nil
}

type TrailerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TrailerName      string                 `protobuf:"bytes,1,opt,name=trailer_name,json=trailerName,proto3" json:"trailer_name,omitempty"`
	TrailerUrlFormat string                 `protobuf:"bytes,2,opt,name=trailer_url_format,json=trailerUrlFormat,proto3" json:"trailer_url_format,omitempty"`
	Trailer_480P     *TrailerType           `protobuf:"bytes,3,opt,name=trailer_480p,json=trailer480p,proto3" json:"trailer_480p,omitempty"`
	TrailerMax       *TrailerType           `protobuf:"bytes,4,opt,name=trailer_max,json=trailerMax,proto3" json:"trailer_max,omitempty"`
	Microtrailer     *TrailerType           `protobuf:"bytes,5,opt,name=microtrailer,proto3" json:"microtrailer,omitempty"`
	ScreenshotMedium string                 `protobuf:"bytes,10,opt,name=screenshot_medium,json=screenshotMedium,proto3" json:"screenshot_medium,omitempty"`
	ScreenshotFull   string                 `protobuf:"bytes,11,opt,name=screenshot_full,json=screenshotFull,proto3" json:"screenshot_full,omitempty"`
	TrailerBaseId    int32                  `protobuf:"varint,12,opt,name=trailer_base_id,json=trailerBaseId,proto3" json:"trailer_base_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrailerInfo) Reset() {
	*x = TrailerInfo{}
	mi := &file_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrailerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrailerInfo) ProtoMessage() {}

func (x *TrailerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrailerInfo.ProtoReflect.Descriptor instead.
func (*TrailerInfo) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{16}
}

func (x *TrailerInfo) GetTrailerName() string {
	if x != nil {
		return x.TrailerName
	}
	return ""
}

func (x *TrailerInfo) GetTrailerUrlFormat() string {
	if x != nil {
		return x.TrailerUrlFormat
	}
	return ""
}

func (x *TrailerInfo) GetTrailer_480P() *TrailerType {
	if x != nil {
		return x.Trailer_480P
	}
	return nil
}

func (x *TrailerInfo) GetTrailerMax() *TrailerType {
	if x != nil {
		return x.TrailerMax
	}
	return nil
}

func (x *TrailerInfo) GetMicrotrailer() *TrailerType {
	if x != nil {
		return x.Microtrailer
	}
	return nil
}

func (x *TrailerInfo) GetScreenshotMedium() string {
	if x != nil {
		return x.ScreenshotMedium
	}
	return ""
}

func (x *TrailerInfo) GetScreenshotFull() string {
	if x != nil {
		return x.ScreenshotFull
	}
	return ""
}

func (x *TrailerInfo) GetTrailerBaseId() int32 {
	if x != nil {
		return x.TrailerBaseId
	}
	return 0
}

type TrailerType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrailerType) Reset() {
	*x = TrailerType{}
	mi := &file_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrailerType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrailerType) ProtoMessage() {}

func (x *TrailerType) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrailerType.ProtoReflect.Descriptor instead.
func (*TrailerType) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{17}
}

func (x *TrailerType) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TrailerType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SupportLanguage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Elanguage           int32                  `protobuf:"varint,1,opt,name=elanguage,proto3" json:"elanguage,omitempty"`
	Eadditionallanguage int32                  `protobuf:"varint,5,opt,name=eadditionallanguage,proto3" json:"eadditionallanguage,omitempty"`
	Supported           bool                   `protobuf:"varint,2,opt,name=supported,proto3" json:"supported,omitempty"`
	FullAudio           bool                   `protobuf:"varint,3,opt,name=full_audio,json=fullAudio,proto3" json:"full_audio,omitempty"`
	Subtitles           bool                   `protobuf:"varint,4,opt,name=subtitles,proto3" json:"subtitles,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SupportLanguage) Reset() {
	*x = SupportLanguage{}
	mi := &file_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportLanguage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportLanguage) ProtoMessage() {}

func (x *SupportLanguage) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportLanguage.ProtoReflect.Descriptor instead.
func (*SupportLanguage) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{18}
}

func (x *SupportLanguage) GetElanguage() int32 {
	if x != nil {
		return x.Elanguage
	}
	return 0
}

func (x *SupportLanguage) GetEadditionallanguage() int32 {
	if x != nil {
		return x.Eadditionallanguage
	}
	return 0
}

func (x *SupportLanguage) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *SupportLanguage) GetFullAudio() bool {
	if x != nil {
		return x.FullAudio
	}
	return false
}

func (x *SupportLanguage) GetSubtitles() bool {
	if x != nil {
		return x.Subtitles
	}
	return false
}

type FreeWeekend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     uint32                 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       uint32                 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeWeekend) Reset() {
	*x = FreeWeekend{}
	mi := &file_store_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeWeekend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeWeekend) ProtoMessage() {}

func (x *FreeWeekend) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeWeekend.ProtoReflect.Descriptor instead.
func (*FreeWeekend) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{19}
}

func (x *FreeWeekend) GetStartTime() uint32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FreeWeekend) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FreeWeekend) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UserFilterFailure struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	FilterFailure                uint32                 `protobuf:"varint,1,opt,name=filter_failure,json=filterFailure,proto3" json:"filter_failure,omitempty"` //enum
	AlreadyOwned                 bool                   `protobuf:"varint,5,opt,name=already_owned,json=alreadyOwned,proto3" json:"already_owned,omitempty"`
	OnWishlist                   bool                   `protobuf:"varint,6,opt,name=on_wishlist,json=onWishlist,proto3" json:"on_wishlist,omitempty"`
	Ignored                      bool                   `protobuf:"varint,7,opt,name=ignored,proto3" json:"ignored,omitempty"`
	NotInUsersLanguage           bool                   `protobuf:"varint,10,opt,name=not_in_users_language,json=notInUsersLanguage,proto3" json:"not_in_users_language,omitempty"`
	NotOnUsersPlatform           bool                   `protobuf:"varint,11,opt,name=not_on_users_platform,json=notOnUsersPlatform,proto3" json:"not_on_users_platform,omitempty"`
	DemoForOwnedGame             bool                   `protobuf:"varint,12,opt,name=demo_for_owned_game,json=demoForOwnedGame,proto3" json:"demo_for_owned_game,omitempty"`
	DlcForUnownedGame            bool                   `protobuf:"varint,13,opt,name=dlc_for_unowned_game,json=dlcForUnownedGame,proto3" json:"dlc_for_unowned_game,omitempty"`
	NonpreferredProductType      bool                   `protobuf:"varint,20,opt,name=nonpreferred_product_type,json=nonpreferredProductType,proto3" json:"nonpreferred_product_type,omitempty"`
	ExcludedTagids               []uint32               `protobuf:"varint,21,rep,packed,name=excluded_tagids,json=excludedTagids,proto3" json:"excluded_tagids,omitempty"`
	ExcludedContentDescriptorids []uint32               `protobuf:"varint,30,rep,packed,name=excluded_content_descriptorids,json=excludedContentDescriptorids,proto3" json:"excluded_content_descriptorids,omitempty"` //enum
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *UserFilterFailure) Reset() {
	*x = UserFilterFailure{}
	mi := &file_store_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilterFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilterFailure) ProtoMessage() {}

func (x *UserFilterFailure) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilterFailure.ProtoReflect.Descriptor instead.
func (*UserFilterFailure) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{20}
}

func (x *UserFilterFailure) GetFilterFailure() uint32 {
	if x != nil {
		return x.FilterFailure
	}
	return 0
}

func (x *UserFilterFailure) GetAlreadyOwned() bool {
	if x != nil {
		return x.AlreadyOwned
	}
	return false
}

func (x *UserFilterFailure) GetOnWishlist() bool {
	if x != nil {
		return x.OnWishlist
	}
	return false
}

func (x *UserFilterFailure) GetIgnored() bool {
	if x != nil {
		return x.Ignored
	}
	return false
}

func (x *UserFilterFailure) GetNotInUsersLanguage() bool {
	if x != nil {
		return x.NotInUsersLanguage
	}
	return false
}

func (x *UserFilterFailure) GetNotOnUsersPlatform() bool {
	if x != nil {
		return x.NotOnUsersPlatform
	}
	return false
}

func (x *UserFilterFailure) GetDemoForOwnedGame() bool {
	if x != nil {
		return x.DemoForOwnedGame
	}
	return false
}

func (x *UserFilterFailure) GetDlcForUnownedGame() bool {
	if x != nil {
		return x.DlcForUnownedGame
	}
	return false
}

func (x *UserFilterFailure) GetNonpreferredProductType() bool {
	if x != nil {
		return x.NonpreferredProductType
	}
	return false
}

func (x *UserFilterFailure) GetExcludedTagids() []uint32 {
	if x != nil {
		return x.ExcludedTagids
	}
	return nil
}

func (x *UserFilterFailure) GetExcludedContentDescriptorids() []uint32 {
	if x != nil {
		return x.ExcludedContentDescriptorids
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkType      uint32                 `protobuf:"varint,1,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"` //enum
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_store_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{21}
}

func (x *Link) GetLinkType() uint32 {
	if x != nil {
		return x.LinkType
	}
	return 0
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\x05steam\":\n" +
	"\x05Store\x121\n" +
	"\vstore_items\x18\x01 \x03(\v2\x10.steam.StoreItemR\n" +
	"storeItems\"\xa2\x0e\n" +
	"\tStoreItem\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\rR\bitemType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\rR\asuccess\x12\x18\n" +
	"\avisible\x18\x04 \x01(\bR\avisible\x12K\n" +
	"\"unvailable_for_country_restriction\x18\x05 \x01(\bR\x1funvailableForCountryRestriction\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12$\n" +
	"\x0estore_url_path\x18\a \x01(\tR\fstoreUrlPath\x12\x14\n" +
	"\x05appid\x18\t \x01(\rR\x05appid\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\rR\x04type\x12%\n" +
	"\x0eincluded_types\x18\v \x03(\rR\rincludedTypes\x12'\n" +
	"\x0fincluded_appids\x18\f \x03(\rR\x0eincludedAppids\x12\x17\n" +
	"\ais_free\x18\r \x01(\bR\x06isFree\x12&\n" +
	"\x0fis_early_access\x18\x0e \x01(\bR\risEarlyAccess\x127\n" +
	"\rrelated_items\x18\x0f \x01(\v2\x12.steam.RelatedItemR\frelatedItems\x12:\n" +
	"\x0eincluded_items\x18\x10 \x01(\v2\x13.steam.IncludedItemR\rincludedItems\x123\n" +
	"\x15content_descriptorids\x18\x14 \x03(\rR\x14contentDescriptorids\x12\x16\n" +
	"\x06tagids\x18\x15 \x03(\rR\x06tagids\x12/\n" +
	"\n" +
	"categories\x18\x16 \x01(\v2\x0f.steam.CategoryR\n" +
	"categories\x12'\n" +
	"\areviews\x18\x17 \x01(\v2\r.steam.ReviewR\areviews\x12/\n" +
	"\n" +
	"basic_info\x18\x18 \x01(\v2\x10.steam.BasicInfoR\tbasicInfo\x12\x1e\n" +
	"\x04tags\x18\x19 \x03(\v2\n" +
	".steam.TagR\x04tags\x12%\n" +
	"\x06assets\x18\x1e \x01(\v2\r.steam.AssetsR\x06assets\x12(\n" +
	"\arelease\x18\x1f \x01(\v2\x0e.steam.ReleaseR\arelease\x12\x1c\n" +
	"\tplatforms\x18  \x01(\rR\tplatforms\x12\x1f\n" +
	"\vgame_rating\x18! \x01(\rR\n" +
	"gameRating\x12?\n" +
	"\x14best_purchase_option\x18( \x01(\v2\r.steam.OptionR\x12bestPurchaseOption\x128\n" +
	"\x10purchase_options\x18) \x03(\v2\r.steam.OptionR\x0fpurchaseOptions\x12/\n" +
	"\vaccessories\x18* \x03(\v2\r.steam.OptionR\vaccessories\x12?\n" +
	"\x14self_purchase_option\x18+ \x01(\v2\r.steam.OptionR\x12selfPurchaseOption\x124\n" +
	"\vscreenshots\x182 \x01(\v2\x12.steam.ScreenShotsR\vscreenshots\x12*\n" +
	"\btrailers\x183 \x03(\v2\x0e.steam.TrailerR\btrailers\x12G\n" +
	"\x13supported_languages\x184 \x03(\v2\x16.steam.SupportLanguageR\x12supportedLanguages\x125\n" +
	"\x17store_url_path_override\x185 \x01(\tR\x14storeUrlPathOverride\x125\n" +
	"\ffree_weekend\x186 \x01(\v2\x12.steam.FreeWeekendR\vfreeWeekend\x12\x1a\n" +
	"\bunlisted\x187 \x01(\bR\bunlisted\x12\x1d\n" +
	"\n" +
	"game_count\x188 \x01(\rR\tgameCount\x12#\n" +
	"\rinternal_name\x189 \x01(\tR\finternalName\x12)\n" +
	"\x10full_description\x18: \x01(\tR\x0ffullDescription\x12.\n" +
	"\x13is_free_temporarily\x18; \x01(\bR\x11isFreeTemporarily\x12G\n" +
	"\x18assets_without_overrides\x18< \x01(\v2\r.steam.AssetsR\x16assetsWithoutOverrides\x12H\n" +
	"\x13user_filter_failure\x18F \x01(\v2\x18.steam.UserFilterFailureR\x11userFilterFailure\x12!\n" +
	"\x05links\x18G \x03(\v2\v.steam.LinkR\x05links\"\x97\x04\n" +
	"\x06Assets\x12(\n" +
	"\x10asset_url_format\x18\x01 \x01(\tR\x0eassetUrlFormat\x12!\n" +
	"\fmain_capsule\x18\x02 \x01(\tR\vmainCapsule\x12#\n" +
	"\rsmall_capsule\x18\x03 \x01(\tR\fsmallCapsule\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\x12%\n" +
	"\x0epackage_header\x18\x05 \x01(\tR\rpackageHeader\x12'\n" +
	"\x0fpage_background\x18\x06 \x01(\tR\x0epageBackground\x12!\n" +
	"\fhero_capsule\x18\a \x01(\tR\vheroCapsule\x12&\n" +
	"\x0fhero_capsule_2x\x18\b \x01(\tR\rheroCapsule2x\x12'\n" +
	"\x0flibrary_capsule\x18\t \x01(\tR\x0elibraryCapsule\x12,\n" +
	"\x12library_capsule_2x\x18\n" +
	" \x01(\tR\x10libraryCapsule2x\x12!\n" +
	"\flibrary_hero\x18\v \x01(\tR\vlibraryHero\x12&\n" +
	"\x0flibrary_hero_2x\x18\f \x01(\tR\rlibraryHero2x\x12%\n" +
	"\x0ecommunity_icon\x18\r \x01(\tR\rcommunityIcon\x12\x1f\n" +
	"\vclan_avatar\x18\x0e \x01(\tR\n" +
	"clanAvatar\"\xfa\b\n" +
	"\x06Option\x12\x1c\n" +
	"\tpackageid\x18\x01 \x01(\x05R\tpackageid\x12\x1a\n" +
	"\bbundleid\x18\x02 \x01(\x05R\bbundleid\x120\n" +
	"\x14purchase_option_name\x18\x03 \x01(\tR\x12purchaseOptionName\x12/\n" +
	"\x14final_price_in_cents\x18\x05 \x01(\x03R\x11finalPriceInCents\x125\n" +
	"\x17original_price_in_cents\x18\x06 \x01(\x03R\x14originalPriceInCents\x128\n" +
	"\x19user_final_price_in_cents\x18\a \x01(\x03R\x15userFinalPriceInCents\x122\n" +
	"\x15formatted_final_price\x18\b \x01(\tR\x13formattedFinalPrice\x128\n" +
	"\x18formatted_original_price\x18\t \x01(\tR\x16formattedOriginalPrice\x12!\n" +
	"\fdiscount_pct\x18\n" +
	" \x01(\x05R\vdiscountPct\x12*\n" +
	"\x11user_discount_pct\x18\v \x01(\x05R\x0fuserDiscountPct\x12.\n" +
	"\x13bundle_discount_pct\x18\f \x01(\x05R\x11bundleDiscountPct\x12)\n" +
	"\x10active_discounts\x18\x14 \x03(\bR\x0factiveDiscounts\x122\n" +
	"\x15user_active_discounts\x18\x15 \x03(\bR\x13userActiveDiscounts\x12-\n" +
	"\x12inactive_discounts\x18\x16 \x03(\bR\x11inactiveDiscounts\x12*\n" +
	"\x11user_can_purchase\x18\x1e \x01(\bR\x0fuserCanPurchase\x128\n" +
	"\x19user_can_purchase_as_gift\x18\x1f \x01(\bR\x15userCanPurchaseAsGift\x122\n" +
	"\x15is_commercial_license\x18( \x01(\bR\x13isCommercialLicense\x12?\n" +
	"\x1cshould_suppress_discount_pct\x18) \x01(\bR\x19shouldSuppressDiscountPct\x12F\n" +
	" hide_discount_pct_for_compliance\x18* \x01(\bR\x1chideDiscountPctForCompliance\x12.\n" +
	"\x13included_game_count\x18+ \x01(\x05R\x11includedGameCount\x12>\n" +
	"\x1clowest_recent_price_in_cents\x18, \x01(\x03R\x18lowestRecentPriceInCents\x12+\n" +
	"\x11requires_shipping\x18- \x01(\bR\x10requiresShipping\x12'\n" +
	"\x0frecurrence_info\x18. \x01(\bR\x0erecurrenceInfo\"\xb4\x01\n" +
	"\bCategory\x12@\n" +
	"\x1csupported_player_categoryids\x18\x02 \x01(\rR\x1asupportedPlayerCategoryids\x12/\n" +
	"\x13feature_categoryids\x18\x03 \x01(\rR\x12featureCategoryids\x125\n" +
	"\x16controller_categoryids\x18\x04 \x01(\rR\x15controllerCategoryids\"\xab\x01\n" +
	"\vScreenShots\x12G\n" +
	"\x14all_ages_screenshots\x18\x02 \x03(\v2\x15.steam.ScreenShotsAgeR\x12allAgesScreenshots\x12S\n" +
	"\x1amature_content_screenshots\x18\x03 \x03(\v2\x15.steam.ScreenShotsAgeR\x18matureContentScreenshots\"F\n" +
	"\x0eScreenShotsAge\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x05R\aordinal\"0\n" +
	"\vRelatedItem\x12!\n" +
	"\fparent_appid\x18\x01 \x01(\rR\vparentAppid\"\x84\x01\n" +
	"\fIncludedItem\x125\n" +
	"\rincluded_apps\x18\x01 \x03(\v2\x10.steam.StoreItemR\fincludedApps\x12=\n" +
	"\x11included_packages\x18\x02 \x03(\v2\x10.steam.StoreItemR\x10includedPackages\"\xf9\x01\n" +
	"\tBasicInfo\x12+\n" +
	"\x11short_description\x18\x01 \x01(\tR\x10shortDescription\x120\n" +
	"\n" +
	"publishers\x18\x02 \x03(\v2\x10.steam.PublisherR\n" +
	"publishers\x120\n" +
	"\n" +
	"developers\x18\x03 \x03(\v2\x10.steam.PublisherR\n" +
	"developers\x120\n" +
	"\n" +
	"franchises\x18\x04 \x03(\v2\x10.steam.PublisherR\n" +
	"franchises\x12)\n" +
	"\x10capsule_headline\x18\x05 \x01(\tR\x0fcapsuleHeadline\"V\n" +
	"\tPublisher\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x17creator_clan_account_id\x18\x02 \x01(\rR\x14creatorClanAccountId\"\x82\x01\n" +
	"\x06Review\x129\n" +
	"\x10summary_filtered\x18\x01 \x01(\v2\x0e.steam.SummaryR\x0fsummaryFiltered\x12=\n" +
	"\x12summary_unfiltered\x18\x02 \x01(\v2\x0e.steam.SummaryR\x11summaryUnfiltered\"\xa8\x01\n" +
	"\aSummary\x12!\n" +
	"\freview_count\x18\x01 \x01(\rR\vreviewCount\x12)\n" +
	"\x10percent_positive\x18\x02 \x01(\x05R\x0fpercentPositive\x12!\n" +
	"\freview_score\x18\x03 \x01(\x05R\vreviewScore\x12,\n" +
	"\x12review_score_label\x18\x04 \x01(\tR\x10reviewScoreLabel\"3\n" +
	"\x03Tag\x12\x14\n" +
	"\x05tagid\x18\x01 \x01(\rR\x05tagid\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\"\x97\x04\n" +
	"\aRelease\x12,\n" +
	"\x12steam_release_date\x18\x01 \x01(\rR\x10steamReleaseDate\x122\n" +
	"\x15original_release_date\x18\x02 \x01(\rR\x13originalReleaseDate\x12=\n" +
	"\x1boriginal_steam_release_date\x18\x03 \x01(\rR\x18originalSteamReleaseDate\x12$\n" +
	"\x0eis_coming_soon\x18\x04 \x01(\bR\fisComingSoon\x12\x1d\n" +
	"\n" +
	"is_preload\x18\x05 \x01(\bR\tisPreload\x12=\n" +
	"\x1bcustom_release_date_message\x18\x06 \x01(\tR\x18customReleaseDateMessage\x127\n" +
	"\x18is_abridged_release_date\x18\a \x01(\bR\x15isAbridgedReleaseDate\x12.\n" +
	"\x13coming_soon_display\x18\b \x01(\tR\x11comingSoonDisplay\x12&\n" +
	"\x0fis_early_access\x18\n" +
	" \x01(\bR\risEarlyAccess\x12(\n" +
	"\x10mac_release_date\x18\x14 \x01(\rR\x0emacReleaseDate\x12,\n" +
	"\x12linux_release_date\x18\x15 \x01(\rR\x10linuxReleaseDate\"x\n" +
	"\aTrailer\x122\n" +
	"\n" +
	"highlights\x18\x01 \x01(\v2\x12.steam.TrailerInfoR\n" +
	"highlights\x129\n" +
	"\x0eother_trailers\x18\x02 \x01(\v2\x12.steam.TrailerInfoR\rotherTrailers\"\x80\x03\n" +
	"\vTrailerInfo\x12!\n" +
	"\ftrailer_name\x18\x01 \x01(\tR\vtrailerName\x12,\n" +
	"\x12trailer_url_format\x18\x02 \x01(\tR\x10trailerUrlFormat\x125\n" +
	"\ftrailer_480p\x18\x03 \x01(\v2\x12.steam.TrailerTypeR\vtrailer480p\x123\n" +
	"\vtrailer_max\x18\x04 \x01(\v2\x12.steam.TrailerTypeR\n" +
	"trailerMax\x126\n" +
	"\fmicrotrailer\x18\x05 \x01(\v2\x12.steam.TrailerTypeR\fmicrotrailer\x12+\n" +
	"\x11screenshot_medium\x18\n" +
	" \x01(\tR\x10screenshotMedium\x12'\n" +
	"\x0fscreenshot_full\x18\v \x01(\tR\x0escreenshotFull\x12&\n" +
	"\x0ftrailer_base_id\x18\f \x01(\x05R\rtrailerBaseId\"=\n" +
	"\vTrailerType\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xbc\x01\n" +
	"\x0fSupportLanguage\x12\x1c\n" +
	"\telanguage\x18\x01 \x01(\x05R\telanguage\x120\n" +
	"\x13eadditionallanguage\x18\x05 \x01(\x05R\x13eadditionallanguage\x12\x1c\n" +
	"\tsupported\x18\x02 \x01(\bR\tsupported\x12\x1d\n" +
	"\n" +
	"full_audio\x18\x03 \x01(\bR\tfullAudio\x12\x1c\n" +
	"\tsubtitles\x18\x04 \x01(\bR\tsubtitles\"[\n" +
	"\vFreeWeekend\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\rR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\rR\aendTime\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x8b\x04\n" +
	"\x11UserFilterFailure\x12%\n" +
	"\x0efilter_failure\x18\x01 \x01(\rR\rfilterFailure\x12#\n" +
	"\ralready_owned\x18\x05 \x01(\bR\falreadyOwned\x12\x1f\n" +
	"\von_wishlist\x18\x06 \x01(\bR\n" +
	"onWishlist\x12\x18\n" +
	"\aignored\x18\a \x01(\bR\aignored\x121\n" +
	"\x15not_in_users_language\x18\n" +
	" \x01(\bR\x12notInUsersLanguage\x121\n" +
	"\x15not_on_users_platform\x18\v \x01(\bR\x12notOnUsersPlatform\x12-\n" +
	"\x13demo_for_owned_game\x18\f \x01(\bR\x10demoForOwnedGame\x12/\n" +
	"\x14dlc_for_unowned_game\x18\r \x01(\bR\x11dlcForUnownedGame\x12:\n" +
	"\x19nonpreferred_product_type\x18\x14 \x01(\bR\x17nonpreferredProductType\x12'\n" +
	"\x0fexcluded_tagids\x18\x15 \x03(\rR\x0eexcludedTagids\x12D\n" +
	"\x1eexcluded_content_descriptorids\x18\x1e \x03(\rR\x1cexcludedContentDescriptorids\"5\n" +
	"\x04Link\x12\x1b\n" +
	"\tlink_type\x18\x01 \x01(\rR\blinkType\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03urlB\vZ\t../Protocb\x06proto3"

var (
	file_store_proto_rawDescOnce sync.Once
	file_store_proto_rawDescData []byte
)

func file_store_proto_rawDescGZIP() []byte {
	file_store_proto_rawDescOnce.Do(func() {
		file_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)))
	})
	return file_store_proto_rawDescData
}

var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_store_proto_goTypes = []any{
	(*Store)(nil),             // 0: steam.Store
	(*StoreItem)(nil),         // 1: steam.StoreItem
	(*Assets)(nil),            // 2: steam.Assets
	(*Option)(nil),            // 3: steam.Option
	(*Category)(nil),          // 4: steam.Category
	(*ScreenShots)(nil),       // 5: steam.ScreenShots
	(*ScreenShotsAge)(nil),    // 6: steam.ScreenShotsAge
	(*RelatedItem)(nil),       // 7: steam.RelatedItem
	(*IncludedItem)(nil),      // 8: steam.IncludedItem
	(*BasicInfo)(nil),         // 9: steam.BasicInfo
	(*Publisher)(nil),         // 10: steam.Publisher
	(*Review)(nil),            // 11: steam.Review
	(*Summary)(nil),           // 12: steam.Summary
	(*Tag)(nil),               // 13: steam.Tag
	(*Release)(nil),           // 14: steam.Release
	(*Trailer)(nil),           // 15: steam.Trailer
	(*TrailerInfo)(nil),       // 16: steam.TrailerInfo
	(*TrailerType)(nil),       // 17: steam.TrailerType
	(*SupportLanguage)(nil),   // 18: steam.SupportLanguage
	(*FreeWeekend)(nil),       // 19: steam.FreeWeekend
	(*UserFilterFailure)(nil), // 20: steam.UserFilterFailure
	(*Link)(nil),              // 21: steam.Link
}
var file_store_proto_depIdxs = []int32{
	1,  // 0: steam.Store.store_items:type_name -> steam.StoreItem
	7,  // 1: steam.StoreItem.related_items:type_name -> steam.RelatedItem
	8,  // 2: steam.StoreItem.included_items:type_name -> steam.IncludedItem
	4,  // 3: steam.StoreItem.categories:type_name -> steam.Category
	11, // 4: steam.StoreItem.reviews:type_name -> steam.Review
	9,  // 5: steam.StoreItem.basic_info:type_name -> steam.BasicInfo
	13, // 6: steam.StoreItem.tags:type_name -> steam.Tag
	2,  // 7: steam.StoreItem.assets:type_name -> steam.Assets
	14, // 8: steam.StoreItem.release:type_name -> steam.Release
	3,  // 9: steam.StoreItem.best_purchase_option:type_name -> steam.Option
	3,  // 10: steam.StoreItem.purchase_options:type_name -> steam.Option
	3,  // 11: steam.StoreItem.accessories:type_name -> steam.Option
	3,  // 12: steam.StoreItem.self_purchase_option:type_name -> steam.Option
	5,  // 13: steam.StoreItem.screenshots:type_name -> steam.ScreenShots
	15, // 14: steam.StoreItem.trailers:type_name -> steam.Trailer
	18, // 15: steam.StoreItem.supported_languages:type_name -> steam.SupportLanguage
	19, // 16: steam.StoreItem.free_weekend:type_name -> steam.FreeWeekend
	2,  // 17: steam.StoreItem.assets_without_overrides:type_name -> steam.Assets
	20, // 18: steam.StoreItem.user_filter_failure:type_name -> steam.UserFilterFailure
	21, // 19: steam.StoreItem.links:type_name -> steam.Link
	6,  // 20: steam.ScreenShots.all_ages_screenshots:type_name -> steam.ScreenShotsAge
	6,  // 21: steam.ScreenShots.mature_content_screenshots:type_name -> steam.ScreenShotsAge
	1,  // 22: steam.IncludedItem.included_apps:type_name -> steam.StoreItem
	1,  // 23: steam.IncludedItem.included_packages:type_name -> steam.StoreItem
	10, // 24: steam.BasicInfo.publishers:type_name -> steam.Publisher
	10, // 25: steam.BasicInfo.developers:type_name -> steam.Publisher
	10, // 26: steam.BasicInfo.franchises:type_name -> steam.Publisher
	12, // 27: steam.Review.summary_filtered:type_name -> steam.Summary
	12, // 28: steam.Review.summary_unfiltered:type_name -> steam.Summary
	16, // 29: steam.Trailer.highlights:type_name -> steam.TrailerInfo
	16, // 30: steam.Trailer.other_trailers:type_name -> steam.TrailerInfo
	17, // 31: steam.TrailerInfo.trailer_480p:type_name -> steam.TrailerType
	17, // 32: steam.TrailerInfo.trailer_max:type_name -> steam.TrailerType
	17, // 33: steam.TrailerInfo.microtrailer:type_name -> steam.TrailerType
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
